"""Generate Strings.<culture>.resx satellite resource files from a single
translation table, keeping every locale's key set exactly in sync with the
base Strings.resx. Companion to pdf-lite-viewer's identical language set:
es, fr, de, it, pt, pt-BR, ja, ko, zh-Hans, zh-Hant, ru, uk, ar.

Run after editing TRANSLATIONS; it overwrites the Strings.<culture>.resx
files under src/EpubLiteReader/.
"""
from __future__ import annotations

from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SRC = ROOT / "src" / "EpubLiteReader"

# Keys in the same order as the base Strings.resx.
ORDER = [
    "AppTitle", "MainWindowTitleFormat", "Open", "OpenTooltip", "Facing",
    "FacingTooltip", "Single", "SingleTooltip", "Scroll", "ScrollTooltip",
    "PrevPageTooltip", "NextPageTooltip", "FontOutTooltip", "FontInTooltip",
    "Theme", "ThemeTooltip", "Search", "SearchTooltip", "SearchPlaceholder",
    "Settings", "SettingsTooltip", "Print", "PrintTooltip", "FullscreenTooltip",
    "EmptyHint", "OpenSampleBook", "ChapterCountFormat", "ProgressFormat", "OpenFileDialogFilter",
    "OpenFileDialogTitle", "OpenFileErrorMessage", "UnhandledErrorMessage",
    "Chapters", "ChaptersTooltip", "CloseChaptersTooltip", "LoadingChapters",
    "NoChapters", "UntitledChapter", "ChapterLoadFailed", "Bookmarks",
    "NoBookmarks", "FontPublisher", "FontSerif", "FontSans", "ThemeLight",
    "ThemeSepia", "ThemeDark", "LineSpacing", "Margins", "ResetText", "About",
    "AboutMessage", "MetadataFormat", "BookmarkAdded", "BookmarkRemoved",
    "FindNext", "FindPrev", "CloseSearch", "NoSearchResults", "SearchResultsFormat",
]

# Format strings and brand name are language-agnostic; the same literal is
# reused in every locale entry below via these constants.
DASH_FMT = "{0} — {1}"
COUNT_FMT = "/ {0}"
APP_TITLE = "EPUB Lite Reader"


def about_message(tagline: str, no_frills: str, freeware: str) -> str:
    return f"{APP_TITLE}\n{tagline}\n{no_frills}\n\n© 2026 Green Yoga Inc\n{freeware}"


TRANSLATIONS = {
    "es": {
        "AppTitle": APP_TITLE, "MainWindowTitleFormat": DASH_FMT,
        "Open": "Abrir…", "OpenTooltip": "Abrir un EPUB (Ctrl+O)",
        "Facing": "Doble", "FacingTooltip": "Vista de libro a doble página (2)",
        "Single": "Única", "SingleTooltip": "Página única (1) — pulsa F11 para pantalla completa",
        "Scroll": "Continuo", "ScrollTooltip": "Desplazamiento continuo de capítulos (3)",
        "PrevPageTooltip": "Página anterior (Re Pág)", "NextPageTooltip": "Página siguiente (Av Pág)",
        "FontOutTooltip": "Reducir tamaño de texto (Ctrl+-)", "FontInTooltip": "Aumentar tamaño de texto (Ctrl++)",
        "Theme": "Tema", "ThemeTooltip": "Tema de lectura",
        "Search": "Buscar", "SearchTooltip": "Buscar en el libro (Ctrl+F)", "SearchPlaceholder": "Buscar en el libro…",
        "Settings": "Configuración", "SettingsTooltip": "Tipografía y opciones",
        "Print": "Imprimir…", "PrintTooltip": "Imprimir capítulo actual (Ctrl+P)",
        "FullscreenTooltip": "Pantalla completa (F11)",
        "EmptyHint": "Abre un EPUB  (Ctrl+O)  —  o suelta un archivo aquí",
        "OpenSampleBook": "Abrir libro de ejemplo",
        "ChapterCountFormat": COUNT_FMT, "ProgressFormat": "{0}%",
        "OpenFileDialogFilter": "Archivos EPUB (*.epub)|*.epub", "OpenFileDialogTitle": "Abrir EPUB",
        "OpenFileErrorMessage": 'No se pudo abrir "{0}".\n\n{1}',
        "UnhandledErrorMessage": "Error inesperado:\n\n{0}\n\nDetalles registrados en:\n{1}",
        "Chapters": "Capítulos", "ChaptersTooltip": "Mostrar u ocultar los capítulos (F4)",
        "CloseChaptersTooltip": "Cerrar capítulos", "LoadingChapters": "Cargando capítulos…",
        "NoChapters": "Este libro no tiene tabla de contenidos.", "UntitledChapter": "Capítulo sin título",
        "ChapterLoadFailed": "No se pudieron cargar los capítulos.",
        "Bookmarks": "Marcadores", "NoBookmarks": "Aún no hay marcadores. Pulsa B para añadir uno.",
        "FontPublisher": "Fuente del editor", "FontSerif": "Serif", "FontSans": "Sans-serif",
        "ThemeLight": "Claro", "ThemeSepia": "Sepia", "ThemeDark": "Oscuro",
        "LineSpacing": "Interlineado", "Margins": "Márgenes", "ResetText": "Restablecer ajustes de texto",
        "About": "Acerca de EPUB Lite Reader",
        "AboutMessage": about_message(
            "Lectura de EPUB rápida y clara para Windows.",
            "Sin biblioteca, sin cuenta, sin distracciones.",
            "Gratuito — Licencia MIT",
        ),
        "MetadataFormat": DASH_FMT,
        "BookmarkAdded": "Marcador añadido", "BookmarkRemoved": "Marcador eliminado",
        "FindNext": "Buscar siguiente", "FindPrev": "Buscar anterior", "CloseSearch": "Cerrar",
        "NoSearchResults": "Sin coincidencias", "SearchResultsFormat": "{0} coincidencias",
    },
    "fr": {
        "AppTitle": APP_TITLE, "MainWindowTitleFormat": DASH_FMT,
        "Open": "Ouvrir…", "OpenTooltip": "Ouvrir un EPUB (Ctrl+O)",
        "Facing": "Double", "FacingTooltip": "Mise en page double page (2)",
        "Single": "Simple", "SingleTooltip": "Page unique (1) — F11 pour le plein écran",
        "Scroll": "Continu", "ScrollTooltip": "Défilement continu des chapitres (3)",
        "PrevPageTooltip": "Page précédente (Page préc.)", "NextPageTooltip": "Page suivante (Page suiv.)",
        "FontOutTooltip": "Réduire la taille du texte (Ctrl+-)", "FontInTooltip": "Augmenter la taille du texte (Ctrl++)",
        "Theme": "Thème", "ThemeTooltip": "Thème de lecture",
        "Search": "Rechercher", "SearchTooltip": "Rechercher dans le livre (Ctrl+F)", "SearchPlaceholder": "Rechercher dans le livre…",
        "Settings": "Paramètres", "SettingsTooltip": "Typographie et options",
        "Print": "Imprimer…", "PrintTooltip": "Imprimer le chapitre actuel (Ctrl+P)",
        "FullscreenTooltip": "Plein écran (F11)",
        "EmptyHint": "Ouvrez un EPUB  (Ctrl+O)  —  ou déposez un fichier ici",
        "OpenSampleBook": "Ouvrir un livre d'exemple",
        "ChapterCountFormat": COUNT_FMT, "ProgressFormat": "{0} %",
        "OpenFileDialogFilter": "Fichiers EPUB (*.epub)|*.epub", "OpenFileDialogTitle": "Ouvrir un EPUB",
        "OpenFileErrorMessage": "Impossible d'ouvrir « {0} ».\n\n{1}",
        "UnhandledErrorMessage": "Erreur inattendue :\n\n{0}\n\nDétails consignés dans :\n{1}",
        "Chapters": "Chapitres", "ChaptersTooltip": "Afficher ou masquer les chapitres (F4)",
        "CloseChaptersTooltip": "Fermer les chapitres", "LoadingChapters": "Chargement des chapitres…",
        "NoChapters": "Ce livre n'a pas de table des matières.", "UntitledChapter": "Chapitre sans titre",
        "ChapterLoadFailed": "Impossible de charger les chapitres.",
        "Bookmarks": "Signets", "NoBookmarks": "Aucun signet pour l'instant. Appuyez sur B pour en ajouter un.",
        "FontPublisher": "Police de l'éditeur", "FontSerif": "Serif", "FontSans": "Sans-serif",
        "ThemeLight": "Clair", "ThemeSepia": "Sépia", "ThemeDark": "Sombre",
        "LineSpacing": "Interligne", "Margins": "Marges", "ResetText": "Réinitialiser les réglages de texte",
        "About": "À propos d'EPUB Lite Reader",
        "AboutMessage": about_message(
            "Lecture EPUB rapide et épurée pour Windows.",
            "Sans bibliothèque, sans compte, sans distraction.",
            "Gratuit — Licence MIT",
        ),
        "MetadataFormat": DASH_FMT,
        "BookmarkAdded": "Signet ajouté", "BookmarkRemoved": "Signet supprimé",
        "FindNext": "Suivant", "FindPrev": "Précédent", "CloseSearch": "Fermer",
        "NoSearchResults": "Aucun résultat", "SearchResultsFormat": "{0} résultats",
    },
    "de": {
        "AppTitle": APP_TITLE, "MainWindowTitleFormat": DASH_FMT,
        "Open": "Öffnen…", "OpenTooltip": "EPUB öffnen (Strg+O)",
        "Facing": "Doppel", "FacingTooltip": "Doppelseiten-Ansicht (2)",
        "Single": "Einzeln", "SingleTooltip": "Einzelseite (1) – F11 für Vollbild",
        "Scroll": "Scrollen", "ScrollTooltip": "Fortlaufendes Scrollen durch Kapitel (3)",
        "PrevPageTooltip": "Vorherige Seite (Bild auf)", "NextPageTooltip": "Nächste Seite (Bild ab)",
        "FontOutTooltip": "Schrift verkleinern (Strg+-)", "FontInTooltip": "Schrift vergrößern (Strg++)",
        "Theme": "Thema", "ThemeTooltip": "Lesethema",
        "Search": "Suchen", "SearchTooltip": "Buch durchsuchen (Strg+F)", "SearchPlaceholder": "Im Buch suchen…",
        "Settings": "Einstellungen", "SettingsTooltip": "Typografie und Optionen",
        "Print": "Drucken…", "PrintTooltip": "Aktuelles Kapitel drucken (Strg+P)",
        "FullscreenTooltip": "Vollbild (F11)",
        "EmptyHint": "EPUB öffnen  (Strg+O)  —  oder Datei hier ablegen",
        "OpenSampleBook": "Beispielbuch öffnen",
        "ChapterCountFormat": COUNT_FMT, "ProgressFormat": "{0}%",
        "OpenFileDialogFilter": "EPUB-Dateien (*.epub)|*.epub", "OpenFileDialogTitle": "EPUB öffnen",
        "OpenFileErrorMessage": '„{0}" konnte nicht geöffnet werden.\n\n{1}',
        "UnhandledErrorMessage": "Unerwarteter Fehler:\n\n{0}\n\nDetails protokolliert unter:\n{1}",
        "Chapters": "Kapitel", "ChaptersTooltip": "Kapitel anzeigen oder ausblenden (F4)",
        "CloseChaptersTooltip": "Kapitel schließen", "LoadingChapters": "Kapitel werden geladen…",
        "NoChapters": "Dieses Buch hat kein Inhaltsverzeichnis.", "UntitledChapter": "Unbenanntes Kapitel",
        "ChapterLoadFailed": "Kapitel konnten nicht geladen werden.",
        "Bookmarks": "Lesezeichen", "NoBookmarks": "Noch keine Lesezeichen. Drücken Sie B, um eines hinzuzufügen.",
        "FontPublisher": "Verlagsschrift", "FontSerif": "Serif", "FontSans": "Serifenlos",
        "ThemeLight": "Hell", "ThemeSepia": "Sepia", "ThemeDark": "Dunkel",
        "LineSpacing": "Zeilenabstand", "Margins": "Ränder", "ResetText": "Textoptionen zurücksetzen",
        "About": "Über EPUB Lite Reader",
        "AboutMessage": about_message(
            "Schnelles, klares EPUB-Lesen für Windows.",
            "Keine Bibliothek, kein Konto, keine Ablenkung.",
            "Freeware — MIT-Lizenz",
        ),
        "MetadataFormat": DASH_FMT,
        "BookmarkAdded": "Lesezeichen hinzugefügt", "BookmarkRemoved": "Lesezeichen entfernt",
        "FindNext": "Weitersuchen", "FindPrev": "Rückwärts suchen", "CloseSearch": "Schließen",
        "NoSearchResults": "Keine Treffer", "SearchResultsFormat": "{0} Treffer",
    },
    "it": {
        "AppTitle": APP_TITLE, "MainWindowTitleFormat": DASH_FMT,
        "Open": "Apri…", "OpenTooltip": "Apri un EPUB (Ctrl+O)",
        "Facing": "Doppia", "FacingTooltip": "Impaginazione a doppia pagina (2)",
        "Single": "Singola", "SingleTooltip": "Pagina singola (1) — premi F11 per lo schermo intero",
        "Scroll": "Scorri", "ScrollTooltip": "Scorrimento continuo dei capitoli (3)",
        "PrevPageTooltip": "Pagina precedente (Pagina su)", "NextPageTooltip": "Pagina successiva (Pagina giù)",
        "FontOutTooltip": "Riduci dimensione testo (Ctrl+-)", "FontInTooltip": "Aumenta dimensione testo (Ctrl++)",
        "Theme": "Tema", "ThemeTooltip": "Tema di lettura",
        "Search": "Cerca", "SearchTooltip": "Cerca nel libro (Ctrl+F)", "SearchPlaceholder": "Cerca nel libro…",
        "Settings": "Impostazioni", "SettingsTooltip": "Tipografia e opzioni",
        "Print": "Stampa…", "PrintTooltip": "Stampa il capitolo corrente (Ctrl+P)",
        "FullscreenTooltip": "Schermo intero (F11)",
        "EmptyHint": "Apri un EPUB  (Ctrl+O)  —  oppure trascina qui un file",
        "OpenSampleBook": "Apri libro di esempio",
        "ChapterCountFormat": COUNT_FMT, "ProgressFormat": "{0}%",
        "OpenFileDialogFilter": "File EPUB (*.epub)|*.epub", "OpenFileDialogTitle": "Apri EPUB",
        "OpenFileErrorMessage": 'Impossibile aprire "{0}".\n\n{1}',
        "UnhandledErrorMessage": "Errore imprevisto:\n\n{0}\n\nDettagli registrati in:\n{1}",
        "Chapters": "Capitoli", "ChaptersTooltip": "Mostra o nascondi i capitoli (F4)",
        "CloseChaptersTooltip": "Chiudi capitoli", "LoadingChapters": "Caricamento dei capitoli…",
        "NoChapters": "Questo libro non ha un sommario.", "UntitledChapter": "Capitolo senza titolo",
        "ChapterLoadFailed": "Impossibile caricare i capitoli.",
        "Bookmarks": "Segnalibri", "NoBookmarks": "Nessun segnalibro. Premi B per aggiungerne uno.",
        "FontPublisher": "Carattere dell'editore", "FontSerif": "Serif", "FontSans": "Sans-serif",
        "ThemeLight": "Chiaro", "ThemeSepia": "Seppia", "ThemeDark": "Scuro",
        "LineSpacing": "Interlinea", "Margins": "Margini", "ResetText": "Ripristina impostazioni testo",
        "About": "Informazioni su EPUB Lite Reader",
        "AboutMessage": about_message(
            "Lettura EPUB veloce e pulita per Windows.",
            "Nessuna libreria, nessun account, nessuna distrazione.",
            "Gratuito — Licenza MIT",
        ),
        "MetadataFormat": DASH_FMT,
        "BookmarkAdded": "Segnalibro aggiunto", "BookmarkRemoved": "Segnalibro rimosso",
        "FindNext": "Trova successivo", "FindPrev": "Trova precedente", "CloseSearch": "Chiudi",
        "NoSearchResults": "Nessun risultato", "SearchResultsFormat": "{0} risultati",
    },
    "pt-BR": {
        "AppTitle": APP_TITLE, "MainWindowTitleFormat": DASH_FMT,
        "Open": "Abrir…", "OpenTooltip": "Abrir um EPUB (Ctrl+O)",
        "Facing": "Dupla", "FacingTooltip": "Visualização de livro em página dupla (2)",
        "Single": "Única", "SingleTooltip": "Página única (1) — pressione F11 para tela cheia",
        "Scroll": "Contínuo", "ScrollTooltip": "Rolagem contínua de capítulos (3)",
        "PrevPageTooltip": "Página anterior (Page Up)", "NextPageTooltip": "Próxima página (Page Down)",
        "FontOutTooltip": "Diminuir tamanho do texto (Ctrl+-)", "FontInTooltip": "Aumentar tamanho do texto (Ctrl++)",
        "Theme": "Tema", "ThemeTooltip": "Tema de leitura",
        "Search": "Pesquisar", "SearchTooltip": "Pesquisar no livro (Ctrl+F)", "SearchPlaceholder": "Pesquisar no livro…",
        "Settings": "Configurações", "SettingsTooltip": "Tipografia e opções",
        "Print": "Imprimir…", "PrintTooltip": "Imprimir capítulo atual (Ctrl+P)",
        "FullscreenTooltip": "Tela cheia (F11)",
        "EmptyHint": "Abra um EPUB  (Ctrl+O)  —  ou solte um arquivo aqui",
        "OpenSampleBook": "Abrir livro de exemplo",
        "ChapterCountFormat": COUNT_FMT, "ProgressFormat": "{0}%",
        "OpenFileDialogFilter": "Arquivos EPUB (*.epub)|*.epub", "OpenFileDialogTitle": "Abrir EPUB",
        "OpenFileErrorMessage": 'Não foi possível abrir "{0}".\n\n{1}',
        "UnhandledErrorMessage": "Erro inesperado:\n\n{0}\n\nDetalhes registrados em:\n{1}",
        "Chapters": "Capítulos", "ChaptersTooltip": "Mostrar ou ocultar os capítulos (F4)",
        "CloseChaptersTooltip": "Fechar capítulos", "LoadingChapters": "Carregando capítulos…",
        "NoChapters": "Este livro não tem sumário.", "UntitledChapter": "Capítulo sem título",
        "ChapterLoadFailed": "Não foi possível carregar os capítulos.",
        "Bookmarks": "Marcadores", "NoBookmarks": "Ainda não há marcadores. Pressione B para adicionar um.",
        "FontPublisher": "Fonte da editora", "FontSerif": "Serif", "FontSans": "Sans-serif",
        "ThemeLight": "Claro", "ThemeSepia": "Sépia", "ThemeDark": "Escuro",
        "LineSpacing": "Espaçamento entre linhas", "Margins": "Margens", "ResetText": "Redefinir configurações de texto",
        "About": "Sobre o EPUB Lite Reader",
        "AboutMessage": about_message(
            "Leitura de EPUB rápida e limpa para Windows.",
            "Sem biblioteca, sem conta, sem distrações.",
            "Gratuito — Licença MIT",
        ),
        "MetadataFormat": DASH_FMT,
        "BookmarkAdded": "Marcador adicionado", "BookmarkRemoved": "Marcador removido",
        "FindNext": "Buscar próxima", "FindPrev": "Buscar anterior", "CloseSearch": "Fechar",
        "NoSearchResults": "Nenhum resultado", "SearchResultsFormat": "{0} resultados",
    },
    "ja": {
        "AppTitle": APP_TITLE, "MainWindowTitleFormat": DASH_FMT,
        "Open": "開く…", "OpenTooltip": "EPUBを開く (Ctrl+O)",
        "Facing": "見開き", "FacingTooltip": "見開きページ表示 (2)",
        "Single": "単一", "SingleTooltip": "単一ページ (1) — F11キーで全画面表示",
        "Scroll": "スクロール", "ScrollTooltip": "章を連続スクロール (3)",
        "PrevPageTooltip": "前のページ (Page Up)", "NextPageTooltip": "次のページ (Page Down)",
        "FontOutTooltip": "文字を縮小 (Ctrl+-)", "FontInTooltip": "文字を拡大 (Ctrl++)",
        "Theme": "テーマ", "ThemeTooltip": "読書テーマ",
        "Search": "検索", "SearchTooltip": "本を検索 (Ctrl+F)", "SearchPlaceholder": "本の中を検索…",
        "Settings": "設定", "SettingsTooltip": "文字組みとオプション",
        "Print": "印刷…", "PrintTooltip": "現在の章を印刷 (Ctrl+P)",
        "FullscreenTooltip": "全画面表示 (F11)",
        "EmptyHint": "EPUBを開く (Ctrl+O)  —  またはファイルをここにドロップ",
        "OpenSampleBook": "サンプル本を開く",
        "ChapterCountFormat": COUNT_FMT, "ProgressFormat": "{0}%",
        "OpenFileDialogFilter": "EPUBファイル (*.epub)|*.epub", "OpenFileDialogTitle": "EPUBを開く",
        "OpenFileErrorMessage": '"{0}" を開けませんでした。\n\n{1}',
        "UnhandledErrorMessage": "予期しないエラー:\n\n{0}\n\n詳細はログに記録されました:\n{1}",
        "Chapters": "章", "ChaptersTooltip": "章を表示または非表示にします (F4)",
        "CloseChaptersTooltip": "章を閉じる", "LoadingChapters": "章を読み込んでいます…",
        "NoChapters": "この本には目次がありません。", "UntitledChapter": "無題の章",
        "ChapterLoadFailed": "章を読み込めませんでした。",
        "Bookmarks": "しおり", "NoBookmarks": "しおりはまだありません。Bキーで追加できます。",
        "FontPublisher": "出版社指定のフォント", "FontSerif": "セリフ体", "FontSans": "サンセリフ体",
        "ThemeLight": "ライト", "ThemeSepia": "セピア", "ThemeDark": "ダーク",
        "LineSpacing": "行間", "Margins": "余白", "ResetText": "テキスト設定をリセット",
        "About": "EPUB Lite Readerについて",
        "AboutMessage": about_message(
            "Windows向けの高速でシンプルなEPUBリーダー。",
            "ライブラリなし、アカウントなし、気の散る要素なし。",
            "フリーウェア — MITライセンス",
        ),
        "MetadataFormat": DASH_FMT,
        "BookmarkAdded": "しおりを追加しました", "BookmarkRemoved": "しおりを削除しました",
        "FindNext": "次を検索", "FindPrev": "前を検索", "CloseSearch": "閉じる",
        "NoSearchResults": "一致なし", "SearchResultsFormat": "{0} 件一致",
    },
    "ko": {
        "AppTitle": APP_TITLE, "MainWindowTitleFormat": DASH_FMT,
        "Open": "열기…", "OpenTooltip": "EPUB 열기 (Ctrl+O)",
        "Facing": "마주보기", "FacingTooltip": "마주보는 페이지 보기 (2)",
        "Single": "단일", "SingleTooltip": "단일 페이지 (1) — F11 키로 전체 화면",
        "Scroll": "스크롤", "ScrollTooltip": "장 연속 스크롤 (3)",
        "PrevPageTooltip": "이전 페이지 (Page Up)", "NextPageTooltip": "다음 페이지 (Page Down)",
        "FontOutTooltip": "글자 크기 축소 (Ctrl+-)", "FontInTooltip": "글자 크기 확대 (Ctrl++)",
        "Theme": "테마", "ThemeTooltip": "읽기 테마",
        "Search": "검색", "SearchTooltip": "책 검색 (Ctrl+F)", "SearchPlaceholder": "책에서 찾기…",
        "Settings": "설정", "SettingsTooltip": "타이포그래피 및 옵션",
        "Print": "인쇄…", "PrintTooltip": "현재 장 인쇄 (Ctrl+P)",
        "FullscreenTooltip": "전체 화면 (F11)",
        "EmptyHint": "EPUB 열기  (Ctrl+O)  —  또는 파일을 여기로 끌어다 놓으세요",
        "OpenSampleBook": "샘플 도서 열기",
        "ChapterCountFormat": COUNT_FMT, "ProgressFormat": "{0}%",
        "OpenFileDialogFilter": "EPUB 파일 (*.epub)|*.epub", "OpenFileDialogTitle": "EPUB 열기",
        "OpenFileErrorMessage": '"{0}"을(를) 열 수 없습니다.\n\n{1}',
        "UnhandledErrorMessage": "예기치 않은 오류:\n\n{0}\n\n자세한 내용은 다음 위치에 기록되었습니다:\n{1}",
        "Chapters": "장", "ChaptersTooltip": "장 표시 또는 숨기기 (F4)",
        "CloseChaptersTooltip": "장 닫기", "LoadingChapters": "장을 불러오는 중…",
        "NoChapters": "이 책에는 목차가 없습니다.", "UntitledChapter": "제목 없는 장",
        "ChapterLoadFailed": "장을 불러올 수 없습니다.",
        "Bookmarks": "책갈피", "NoBookmarks": "아직 책갈피가 없습니다. B 키를 눌러 추가하세요.",
        "FontPublisher": "출판사 글꼴", "FontSerif": "세리프", "FontSans": "산세리프",
        "ThemeLight": "라이트", "ThemeSepia": "세피아", "ThemeDark": "다크",
        "LineSpacing": "줄 간격", "Margins": "여백", "ResetText": "텍스트 설정 재설정",
        "About": "EPUB Lite Reader 정보",
        "AboutMessage": about_message(
            "Windows용 빠르고 깔끔한 EPUB 리더.",
            "라이브러리 없음, 계정 없음, 방해 요소 없음.",
            "프리웨어 — MIT 라이선스",
        ),
        "MetadataFormat": DASH_FMT,
        "BookmarkAdded": "책갈피 추가됨", "BookmarkRemoved": "책갈피 삭제됨",
        "FindNext": "다음 찾기", "FindPrev": "이전 찾기", "CloseSearch": "닫기",
        "NoSearchResults": "일치하는 항목 없음", "SearchResultsFormat": "{0}개 일치",
    },
    "zh-Hans": {
        "AppTitle": APP_TITLE, "MainWindowTitleFormat": DASH_FMT,
        "Open": "打开…", "OpenTooltip": "打开 EPUB (Ctrl+O)",
        "Facing": "双页", "FacingTooltip": "双页对照版式 (2)",
        "Single": "单页", "SingleTooltip": "单页 (1) — 按 F11 全屏",
        "Scroll": "滚动", "ScrollTooltip": "连续滚动章节 (3)",
        "PrevPageTooltip": "上一页 (Page Up)", "NextPageTooltip": "下一页 (Page Down)",
        "FontOutTooltip": "缩小文字 (Ctrl+-)", "FontInTooltip": "放大文字 (Ctrl++)",
        "Theme": "主题", "ThemeTooltip": "阅读主题",
        "Search": "搜索", "SearchTooltip": "搜索书籍 (Ctrl+F)", "SearchPlaceholder": "在书中查找…",
        "Settings": "设置", "SettingsTooltip": "排版和选项",
        "Print": "打印…", "PrintTooltip": "打印当前章节 (Ctrl+P)",
        "FullscreenTooltip": "全屏 (F11)",
        "EmptyHint": "打开 EPUB  (Ctrl+O)  — 或将文件拖到此处",
        "OpenSampleBook": "打开示例书籍",
        "ChapterCountFormat": COUNT_FMT, "ProgressFormat": "{0}%",
        "OpenFileDialogFilter": "EPUB 文件 (*.epub)|*.epub", "OpenFileDialogTitle": "打开 EPUB",
        "OpenFileErrorMessage": '无法打开"{0}"。\n\n{1}',
        "UnhandledErrorMessage": "意外错误:\n\n{0}\n\n详细信息已记录到:\n{1}",
        "Chapters": "章节", "ChaptersTooltip": "显示或隐藏章节 (F4)",
        "CloseChaptersTooltip": "关闭章节", "LoadingChapters": "正在加载章节…",
        "NoChapters": "此书没有目录。", "UntitledChapter": "无标题章节",
        "ChapterLoadFailed": "无法加载章节。",
        "Bookmarks": "书签", "NoBookmarks": "还没有书签。按 B 添加一个。",
        "FontPublisher": "出版商字体", "FontSerif": "衬线体", "FontSans": "无衬线体",
        "ThemeLight": "浅色", "ThemeSepia": "护眼", "ThemeDark": "深色",
        "LineSpacing": "行距", "Margins": "页边距", "ResetText": "重置文字设置",
        "About": "关于 EPUB Lite Reader",
        "AboutMessage": about_message(
            "适用于 Windows 的快速、简洁的 EPUB 阅读器。",
            "无需书库，无需账户，没有干扰。",
            "免费软件 — MIT 许可证",
        ),
        "MetadataFormat": DASH_FMT,
        "BookmarkAdded": "已添加书签", "BookmarkRemoved": "已移除书签",
        "FindNext": "查找下一个", "FindPrev": "查找上一个", "CloseSearch": "关闭",
        "NoSearchResults": "无匹配项", "SearchResultsFormat": "{0} 处匹配",
    },
    "zh-Hant": {
        "AppTitle": APP_TITLE, "MainWindowTitleFormat": DASH_FMT,
        "Open": "開啟…", "OpenTooltip": "開啟 EPUB (Ctrl+O)",
        "Facing": "雙頁", "FacingTooltip": "雙頁對照版面 (2)",
        "Single": "單頁", "SingleTooltip": "單頁 (1) — 按 F11 全螢幕",
        "Scroll": "捲動", "ScrollTooltip": "連續捲動章節 (3)",
        "PrevPageTooltip": "上一頁 (Page Up)", "NextPageTooltip": "下一頁 (Page Down)",
        "FontOutTooltip": "縮小文字 (Ctrl+-)", "FontInTooltip": "放大文字 (Ctrl++)",
        "Theme": "主題", "ThemeTooltip": "閱讀主題",
        "Search": "搜尋", "SearchTooltip": "搜尋書籍 (Ctrl+F)", "SearchPlaceholder": "在書中尋找…",
        "Settings": "設定", "SettingsTooltip": "排版與選項",
        "Print": "列印…", "PrintTooltip": "列印目前章節 (Ctrl+P)",
        "FullscreenTooltip": "全螢幕 (F11)",
        "EmptyHint": "開啟 EPUB  (Ctrl+O)  — 或將檔案拖曳至此",
        "OpenSampleBook": "開啟範例書籍",
        "ChapterCountFormat": COUNT_FMT, "ProgressFormat": "{0}%",
        "OpenFileDialogFilter": "EPUB 檔案 (*.epub)|*.epub", "OpenFileDialogTitle": "開啟 EPUB",
        "OpenFileErrorMessage": "無法開啟「{0}」。\n\n{1}",
        "UnhandledErrorMessage": "未預期的錯誤:\n\n{0}\n\n詳細資訊已記錄至:\n{1}",
        "Chapters": "章節", "ChaptersTooltip": "顯示或隱藏章節 (F4)",
        "CloseChaptersTooltip": "關閉章節", "LoadingChapters": "正在載入章節…",
        "NoChapters": "此書沒有目錄。", "UntitledChapter": "無標題章節",
        "ChapterLoadFailed": "無法載入章節。",
        "Bookmarks": "書籤", "NoBookmarks": "尚無書籤。按 B 新增一個。",
        "FontPublisher": "出版商字型", "FontSerif": "襯線體", "FontSans": "無襯線體",
        "ThemeLight": "淺色", "ThemeSepia": "護眼", "ThemeDark": "深色",
        "LineSpacing": "行距", "Margins": "邊界", "ResetText": "重設文字設定",
        "About": "關於 EPUB Lite Reader",
        "AboutMessage": about_message(
            "適用於 Windows 的快速、簡潔 EPUB 閱讀器。",
            "無需書庫、無需帳戶、無干擾。",
            "免費軟體 — MIT 授權",
        ),
        "MetadataFormat": DASH_FMT,
        "BookmarkAdded": "已加入書籤", "BookmarkRemoved": "已移除書籤",
        "FindNext": "尋找下一個", "FindPrev": "尋找上一個", "CloseSearch": "關閉",
        "NoSearchResults": "沒有相符項目", "SearchResultsFormat": "{0} 個相符項目",
    },
    "ru": {
        "AppTitle": APP_TITLE, "MainWindowTitleFormat": DASH_FMT,
        "Open": "Открыть…", "OpenTooltip": "Открыть EPUB (Ctrl+O)",
        "Facing": "Разворот", "FacingTooltip": "Книжный разворот (2)",
        "Single": "Одна", "SingleTooltip": "Одна страница (1) — F11 для полноэкранного режима",
        "Scroll": "Прокрутка", "ScrollTooltip": "Непрерывная прокрутка глав (3)",
        "PrevPageTooltip": "Предыдущая страница (Page Up)", "NextPageTooltip": "Следующая страница (Page Down)",
        "FontOutTooltip": "Уменьшить текст (Ctrl+-)", "FontInTooltip": "Увеличить текст (Ctrl++)",
        "Theme": "Тема", "ThemeTooltip": "Тема чтения",
        "Search": "Поиск", "SearchTooltip": "Поиск по книге (Ctrl+F)", "SearchPlaceholder": "Поиск в книге…",
        "Settings": "Настройки", "SettingsTooltip": "Типографика и параметры",
        "Print": "Печать…", "PrintTooltip": "Печать текущей главы (Ctrl+P)",
        "FullscreenTooltip": "Полноэкранный режим (F11)",
        "EmptyHint": "Откройте EPUB (Ctrl+O)  —  или перетащите файл сюда",
        "OpenSampleBook": "Открыть пример книги",
        "ChapterCountFormat": COUNT_FMT, "ProgressFormat": "{0}%",
        "OpenFileDialogFilter": "Файлы EPUB (*.epub)|*.epub", "OpenFileDialogTitle": "Открыть EPUB",
        "OpenFileErrorMessage": "Не удалось открыть «{0}».\n\n{1}",
        "UnhandledErrorMessage": "Непредвиденная ошибка:\n\n{0}\n\nПодробности записаны в:\n{1}",
        "Chapters": "Главы", "ChaptersTooltip": "Показать или скрыть главы (F4)",
        "CloseChaptersTooltip": "Закрыть главы", "LoadingChapters": "Загрузка глав…",
        "NoChapters": "В этой книге нет оглавления.", "UntitledChapter": "Глава без названия",
        "ChapterLoadFailed": "Не удалось загрузить главы.",
        "Bookmarks": "Закладки", "NoBookmarks": "Закладок пока нет. Нажмите B, чтобы добавить.",
        "FontPublisher": "Шрифт издателя", "FontSerif": "С засечками", "FontSans": "Без засечек",
        "ThemeLight": "Светлая", "ThemeSepia": "Сепия", "ThemeDark": "Тёмная",
        "LineSpacing": "Межстрочный интервал", "Margins": "Поля", "ResetText": "Сбросить настройки текста",
        "About": "О программе EPUB Lite Reader",
        "AboutMessage": about_message(
            "Быстрое и понятное чтение EPUB для Windows.",
            "Без библиотеки, без учётной записи, без отвлечений.",
            "Бесплатно — лицензия MIT",
        ),
        "MetadataFormat": DASH_FMT,
        "BookmarkAdded": "Закладка добавлена", "BookmarkRemoved": "Закладка удалена",
        "FindNext": "Найти далее", "FindPrev": "Найти ранее", "CloseSearch": "Закрыть",
        "NoSearchResults": "Совпадений нет", "SearchResultsFormat": "Совпадений: {0}",
    },
    "uk": {
        "AppTitle": APP_TITLE, "MainWindowTitleFormat": DASH_FMT,
        "Open": "Відкрити…", "OpenTooltip": "Відкрити EPUB (Ctrl+O)",
        "Facing": "Розворот", "FacingTooltip": "Книжковий розворот (2)",
        "Single": "Одна", "SingleTooltip": "Одна сторінка (1) — натисніть F11 для повноекранного режиму",
        "Scroll": "Прокрутка", "ScrollTooltip": "Безперервна прокрутка розділів (3)",
        "PrevPageTooltip": "Попередня сторінка (Page Up)", "NextPageTooltip": "Наступна сторінка (Page Down)",
        "FontOutTooltip": "Зменшити текст (Ctrl+-)", "FontInTooltip": "Збільшити текст (Ctrl++)",
        "Theme": "Тема", "ThemeTooltip": "Тема читання",
        "Search": "Пошук", "SearchTooltip": "Пошук у книзі (Ctrl+F)", "SearchPlaceholder": "Пошук у книзі…",
        "Settings": "Налаштування", "SettingsTooltip": "Типографіка та параметри",
        "Print": "Друк…", "PrintTooltip": "Друк поточного розділу (Ctrl+P)",
        "FullscreenTooltip": "Повноекранний режим (F11)",
        "EmptyHint": "Відкрийте EPUB (Ctrl+O)  —  або перетягніть файл сюди",
        "OpenSampleBook": "Відкрити приклад книги",
        "ChapterCountFormat": COUNT_FMT, "ProgressFormat": "{0}%",
        "OpenFileDialogFilter": "Файли EPUB (*.epub)|*.epub", "OpenFileDialogTitle": "Відкрити EPUB",
        "OpenFileErrorMessage": "Не вдалося відкрити «{0}».\n\n{1}",
        "UnhandledErrorMessage": "Неочікувана помилка:\n\n{0}\n\nПодробиці записано до:\n{1}",
        "Chapters": "Розділи", "ChaptersTooltip": "Показати або приховати розділи (F4)",
        "CloseChaptersTooltip": "Закрити розділи", "LoadingChapters": "Завантаження розділів…",
        "NoChapters": "У цій книзі немає змісту.", "UntitledChapter": "Розділ без назви",
        "ChapterLoadFailed": "Не вдалося завантажити розділи.",
        "Bookmarks": "Закладки", "NoBookmarks": "Закладок ще немає. Натисніть B, щоб додати.",
        "FontPublisher": "Шрифт видавця", "FontSerif": "Із засічками", "FontSans": "Без засічок",
        "ThemeLight": "Світла", "ThemeSepia": "Сепія", "ThemeDark": "Темна",
        "LineSpacing": "Міжрядковий інтервал", "Margins": "Поля", "ResetText": "Скинути налаштування тексту",
        "About": "Про EPUB Lite Reader",
        "AboutMessage": about_message(
            "Швидке й чисте читання EPUB для Windows.",
            "Без бібліотеки, без облікового запису, без відволікань.",
            "Безкоштовно — ліцензія MIT",
        ),
        "MetadataFormat": DASH_FMT,
        "BookmarkAdded": "Закладку додано", "BookmarkRemoved": "Закладку видалено",
        "FindNext": "Знайти далі", "FindPrev": "Знайти раніше", "CloseSearch": "Закрити",
        "NoSearchResults": "Немає збігів", "SearchResultsFormat": "Збігів: {0}",
    },
    "ar": {
        "AppTitle": APP_TITLE, "MainWindowTitleFormat": DASH_FMT,
        "Open": "فتح…", "OpenTooltip": "فتح ملف EPUB (Ctrl+O)",
        "Facing": "صفحتان", "FacingTooltip": "تخطيط كتاب بصفحتين (2)",
        "Single": "صفحة واحدة", "SingleTooltip": "صفحة واحدة (1) — اضغط F11 لملء الشاشة",
        "Scroll": "تمرير", "ScrollTooltip": "تمرير متواصل للفصول (3)",
        "PrevPageTooltip": "الصفحة السابقة (Page Up)", "NextPageTooltip": "الصفحة التالية (Page Down)",
        "FontOutTooltip": "تصغير حجم النص (Ctrl+-)", "FontInTooltip": "تكبير حجم النص (Ctrl++)",
        "Theme": "المظهر", "ThemeTooltip": "مظهر القراءة",
        "Search": "بحث", "SearchTooltip": "البحث في الكتاب (Ctrl+F)", "SearchPlaceholder": "البحث في الكتاب…",
        "Settings": "الإعدادات", "SettingsTooltip": "التنسيق الطباعي والخيارات",
        "Print": "طباعة…", "PrintTooltip": "طباعة الفصل الحالي (Ctrl+P)",
        "FullscreenTooltip": "ملء الشاشة (F11)",
        "EmptyHint": "افتح ملف EPUB (Ctrl+O)  —  أو اسحب ملفًا إلى هنا",
        "OpenSampleBook": "فتح كتاب نموذجي",
        "ChapterCountFormat": COUNT_FMT, "ProgressFormat": "{0}%",
        "OpenFileDialogFilter": "ملفات EPUB (*.epub)|*.epub", "OpenFileDialogTitle": "فتح ملف EPUB",
        "OpenFileErrorMessage": 'تعذّر فتح "{0}".\n\n{1}',
        "UnhandledErrorMessage": "خطأ غير متوقع:\n\n{0}\n\nتم تسجيل التفاصيل في:\n{1}",
        "Chapters": "الفصول", "ChaptersTooltip": "إظهار الفصول أو إخفاؤها (F4)",
        "CloseChaptersTooltip": "إغلاق الفصول", "LoadingChapters": "جارٍ تحميل الفصول…",
        "NoChapters": "لا يحتوي هذا الكتاب على فهرس محتويات.", "UntitledChapter": "فصل بلا عنوان",
        "ChapterLoadFailed": "تعذر تحميل الفصول.",
        "Bookmarks": "الإشارات المرجعية", "NoBookmarks": "لا توجد إشارات مرجعية بعد. اضغط B لإضافة واحدة.",
        "FontPublisher": "خط الناشر", "FontSerif": "بأطراف زخرفية", "FontSans": "بلا أطراف زخرفية",
        "ThemeLight": "فاتح", "ThemeSepia": "بني داكن", "ThemeDark": "داكن",
        "LineSpacing": "تباعد الأسطر", "Margins": "الهوامش", "ResetText": "إعادة ضبط إعدادات النص",
        "About": "حول EPUB Lite Reader",
        "AboutMessage": about_message(
            "قراءة EPUB سريعة ونظيفة على ويندوز.",
            "بلا مكتبة، بلا حساب، بلا تشتيت.",
            "برنامج مجاني — رخصة MIT",
        ),
        "MetadataFormat": DASH_FMT,
        "BookmarkAdded": "تمت إضافة الإشارة المرجعية", "BookmarkRemoved": "تمت إزالة الإشارة المرجعية",
        "FindNext": "البحث عن التالي", "FindPrev": "البحث عن السابق", "CloseSearch": "إغلاق",
        "NoSearchResults": "لا توجد نتائج", "SearchResultsFormat": "{0} نتيجة مطابقة",
    },
}
# European Portuguese: same base as pt-BR, overriding the classic PT-PT vs
# PT-BR markers (ficheiro/arquivo, ecrã/tela, definições/configurações,
# "a carregar"/"carregando", "prima"/"pressione").
TRANSLATIONS["pt"] = {
    **TRANSLATIONS["pt-BR"],
    "SingleTooltip": "Página única (1) — prima F11 para ecrã inteiro",
    "FullscreenTooltip": "Ecrã inteiro (F11)",
    "EmptyHint": "Abra um EPUB  (Ctrl+O)  —  ou largue um ficheiro aqui",
    "OpenFileDialogFilter": "Ficheiros EPUB (*.epub)|*.epub",
    "Settings": "Definições",
    "LoadingChapters": "A carregar capítulos…",
    "ResetText": "Repor definições de texto",
    "NoBookmarks": "Ainda não há marcadores. Prima B para adicionar um.",
}

HEADER = """<?xml version="1.0" encoding="utf-8"?>
<root>
  <resheader name="resmimetype">
    <value>text/microsoft-resx</value>
  </resheader>
  <resheader name="version">
    <value>2.0</value>
  </resheader>
  <resheader name="reader">
    <value>System.Resources.ResXResourceReader, System.Windows.Forms, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089</value>
  </resheader>
  <resheader name="writer">
    <value>System.Resources.ResXResourceWriter, System.Windows.Forms, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089</value>
  </resheader>
"""


def escape(s: str) -> str:
    return s.replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;")


def build() -> None:
    missing_report: list[str] = []
    for locale, values in TRANSLATIONS.items():
        missing = set(ORDER) - set(values)
        extra = set(values) - set(ORDER)
        if missing or extra:
            missing_report.append(f"{locale}: missing={sorted(missing)} extra={sorted(extra)}")
    if missing_report:
        raise SystemExit("Key mismatch:\n" + "\n".join(missing_report))

    for locale, values in TRANSLATIONS.items():
        lines = [HEADER]
        for key in ORDER:
            lines.append(f'  <data name="{key}" xml:space="preserve"><value>{escape(values[key])}</value></data>\n')
        lines.append("</root>\n")
        out = SRC / f"Strings.{locale}.resx"
        out.write_text("".join(lines), encoding="utf-8")
        print(f"Wrote {out}")


if __name__ == "__main__":
    build()
