"""Generate Strings.<culture>.resx satellite resource files from a single
translation table, keeping every locale's key set exactly in sync with the
base Strings.resx. Companion to pdf-lite-viewer's identical language set:
es, fr, de, it, pt, pt-BR, ja, ko, zh-Hans, zh-Hant, ru, uk, ar.

Run after editing TRANSLATIONS; it overwrites the Strings.<culture>.resx
files under src/EpubLiteReader/.
"""
from __future__ import annotations

from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SRC = ROOT / "src" / "EpubLiteReader"

# Keys in the same order as the base Strings.resx.
ORDER = [
    "AppTitle", "MainWindowTitleFormat", "Open", "OpenTooltip", "Facing",
    "FacingTooltip", "Single", "SingleTooltip", "Scroll", "ScrollTooltip",
    "PrevPageTooltip", "NextPageTooltip", "FontOutTooltip", "FontInTooltip",
    "Theme", "ThemeTooltip", "Search", "SearchTooltip", "SearchPlaceholder",
    "Settings", "SettingsTooltip", "Print", "PrintTooltip", "FullscreenTooltip",
    "EmptyHint", "OpenSampleBook", "ChapterCountFormat", "ProgressFormat", "OpenFileDialogFilter",
    "OpenFileDialogTitle", "OpenFileErrorMessage", "UnhandledErrorMessage",
    "Chapters", "ChaptersTooltip", "CloseChaptersTooltip", "LoadingChapters",
    "NoChapters", "UntitledChapter", "ChapterLoadFailed", "Bookmarks",
    "NoBookmarks", "FontPublisher", "FontSerif", "FontSans", "ThemeLight",
    "ThemeSepia", "ThemeDark", "LineSpacing", "Margins", "ResetText", "About",
    "AboutWindowTitleFormat", "AboutVersionFormat", "AboutPublishedBy",
    "AboutBrandBlurb", "AboutWebsiteLink", "AboutPrivacyLink",
    "AboutLicenseLink", "AboutContactSupport", "AboutClose",
    "AboutLicenseUnavailable", "SupportDisclosure", "SupportLoadButton",
    "SupportOpenInBrowser", "SupportEmail", "SupportRetry", "SupportLoading",
    "SupportLoadFailed", "SupportBack", "ContinuousSectionTitleFormat",
    "PageBoxName", "MetadataFormat",
    "FindNext", "FindPrev", "CloseSearch", "NoSearchResults", "SearchResultsFormat",
    "NoReadableContent",
]

# Format strings and brand name are language-agnostic; the same literal is
# reused in every locale entry below via these constants.
DASH_FMT = "{0} — {1}"
COUNT_FMT = "/ {0}"
APP_TITLE = "EPUB Lite Reader"


TRANSLATIONS = {
    "es": {
        "AppTitle": APP_TITLE, "MainWindowTitleFormat": DASH_FMT,
        "Open": "Abrir…", "OpenTooltip": "Abrir un EPUB (Ctrl+O)",
        "Facing": "Doble", "FacingTooltip": "Vista de libro a doble página (2)",
        "Single": "Única", "SingleTooltip": "Página única (1) — pulsa F11 para pantalla completa",
        "Scroll": "Continuo", "ScrollTooltip": "Desplazamiento continuo de capítulos (3)",
        "PrevPageTooltip": "Página anterior (Re Pág)", "NextPageTooltip": "Página siguiente (Av Pág)",
        "FontOutTooltip": "Reducir tamaño de texto (Ctrl+-)", "FontInTooltip": "Aumentar tamaño de texto (Ctrl++)",
        "Theme": "Tema", "ThemeTooltip": "Tema de lectura",
        "Search": "Buscar", "SearchTooltip": "Buscar en el libro (Ctrl+F)", "SearchPlaceholder": "Buscar en el libro…",
        "Settings": "Configuración", "SettingsTooltip": "Tipografía y opciones",
        "Print": "Imprimir…", "PrintTooltip": "Imprimir capítulo actual (Ctrl+P)",
        "FullscreenTooltip": "Pantalla completa (F11)",
        "EmptyHint": "Abre un EPUB  (Ctrl+O)  —  o suelta un archivo aquí",
        "OpenSampleBook": "Abrir libro de ejemplo",
        "ChapterCountFormat": COUNT_FMT, "ProgressFormat": "{0}%",
        "OpenFileDialogFilter": "Archivos EPUB (*.epub)|*.epub", "OpenFileDialogTitle": "Abrir EPUB",
        "OpenFileErrorMessage": 'No se pudo abrir "{0}".\n\n{1}',
        "UnhandledErrorMessage": "Error inesperado:\n\n{0}\n\nDetalles registrados en:\n{1}",
        "Chapters": "Capítulos", "ChaptersTooltip": "Mostrar u ocultar los capítulos (F4)",
        "CloseChaptersTooltip": "Cerrar capítulos", "LoadingChapters": "Cargando capítulos…",
        "NoChapters": "Este libro no tiene tabla de contenidos.", "UntitledChapter": "Capítulo sin título",
        "ChapterLoadFailed": "No se pudieron cargar los capítulos.",
        "Bookmarks": "Marcadores", "NoBookmarks": "Aún no hay marcadores. Pulsa B para añadir uno.",
        "FontPublisher": "Fuente del editor", "FontSerif": "Serif", "FontSans": "Sans-serif",
        "ThemeLight": "Claro", "ThemeSepia": "Sepia", "ThemeDark": "Oscuro",
        "LineSpacing": "Interlineado", "Margins": "Márgenes", "ResetText": "Restablecer ajustes de texto",
        "About": "Acerca de EPUB Lite Reader",
        "AboutWindowTitleFormat": "Acerca de {0}",
        "AboutVersionFormat": "Versión {0}",
        "AboutPublishedBy": "Publicado por Green Yoga Inc.",
        "AboutBrandBlurb": "Green Yoga Inc crea software y herramientas digitales pensadas para la lectura, el bienestar y la tecnología práctica.",
        "AboutWebsiteLink": "Sitio web de Green Yoga",
        "AboutPrivacyLink": "Política de privacidad",
        "AboutLicenseLink": "Licencia MIT",
        "AboutContactSupport": "Contactar con soporte",
        "AboutClose": "Cerrar",
        "AboutLicenseUnavailable": "No se pudo cargar el texto de la licencia. Esta aplicación se distribuye bajo la Licencia MIT.",
        "SupportDisclosure": "Contactar con soporte carga el sitio web de Green Yoga (greenyogainc.com) dentro de esta ventana. Se requiere conexión a internet, y la política de privacidad del sitio de Green Yoga se aplica a cualquier información que envíes.",
        "SupportLoadButton": "Cargar página de soporte",
        "SupportOpenInBrowser": "Abrir en el navegador web",
        "SupportEmail": "Contactar con soporte por correo electrónico",
        "SupportRetry": "Reintentar",
        "SupportLoading": "Cargando página de soporte…",
        "SupportLoadFailed": "No se pudo cargar la página de soporte. Comprueba tu conexión a internet e inténtalo de nuevo, o utiliza una de las opciones que aparecen a continuación.",
        "SupportBack": "Atrás",
        "ContinuousSectionTitleFormat": "Sección {0}",
        "PageBoxName": "Número de capítulo",
        "MetadataFormat": DASH_FMT,
        "FindNext": "Buscar siguiente", "FindPrev": "Buscar anterior", "CloseSearch": "Cerrar",
        "NoSearchResults": "Sin coincidencias", "SearchResultsFormat": "{0} coincidencias",
        "NoReadableContent": "Este libro no tiene páginas legibles.",
    },
    "fr": {
        "AppTitle": APP_TITLE, "MainWindowTitleFormat": DASH_FMT,
        "Open": "Ouvrir…", "OpenTooltip": "Ouvrir un EPUB (Ctrl+O)",
        "Facing": "Double", "FacingTooltip": "Mise en page double page (2)",
        "Single": "Simple", "SingleTooltip": "Page unique (1) — F11 pour le plein écran",
        "Scroll": "Continu", "ScrollTooltip": "Défilement continu des chapitres (3)",
        "PrevPageTooltip": "Page précédente (Page préc.)", "NextPageTooltip": "Page suivante (Page suiv.)",
        "FontOutTooltip": "Réduire la taille du texte (Ctrl+-)", "FontInTooltip": "Augmenter la taille du texte (Ctrl++)",
        "Theme": "Thème", "ThemeTooltip": "Thème de lecture",
        "Search": "Rechercher", "SearchTooltip": "Rechercher dans le livre (Ctrl+F)", "SearchPlaceholder": "Rechercher dans le livre…",
        "Settings": "Paramètres", "SettingsTooltip": "Typographie et options",
        "Print": "Imprimer…", "PrintTooltip": "Imprimer le chapitre actuel (Ctrl+P)",
        "FullscreenTooltip": "Plein écran (F11)",
        "EmptyHint": "Ouvrez un EPUB  (Ctrl+O)  —  ou déposez un fichier ici",
        "OpenSampleBook": "Ouvrir un livre d'exemple",
        "ChapterCountFormat": COUNT_FMT, "ProgressFormat": "{0} %",
        "OpenFileDialogFilter": "Fichiers EPUB (*.epub)|*.epub", "OpenFileDialogTitle": "Ouvrir un EPUB",
        "OpenFileErrorMessage": "Impossible d'ouvrir « {0} ».\n\n{1}",
        "UnhandledErrorMessage": "Erreur inattendue :\n\n{0}\n\nDétails consignés dans :\n{1}",
        "Chapters": "Chapitres", "ChaptersTooltip": "Afficher ou masquer les chapitres (F4)",
        "CloseChaptersTooltip": "Fermer les chapitres", "LoadingChapters": "Chargement des chapitres…",
        "NoChapters": "Ce livre n'a pas de table des matières.", "UntitledChapter": "Chapitre sans titre",
        "ChapterLoadFailed": "Impossible de charger les chapitres.",
        "Bookmarks": "Signets", "NoBookmarks": "Aucun signet pour l'instant. Appuyez sur B pour en ajouter un.",
        "FontPublisher": "Police de l'éditeur", "FontSerif": "Serif", "FontSans": "Sans-serif",
        "ThemeLight": "Clair", "ThemeSepia": "Sépia", "ThemeDark": "Sombre",
        "LineSpacing": "Interligne", "Margins": "Marges", "ResetText": "Réinitialiser les réglages de texte",
        "About": "À propos d'EPUB Lite Reader",
        "AboutWindowTitleFormat": "À propos de {0}",
        "AboutVersionFormat": "Version {0}",
        "AboutPublishedBy": "Publié par Green Yoga Inc.",
        "AboutBrandBlurb": "Green Yoga Inc conçoit des logiciels et des outils numériques pensés pour la lecture, le bien-être et une technologie pratique.",
        "AboutWebsiteLink": "Site web de Green Yoga",
        "AboutPrivacyLink": "Politique de confidentialité",
        "AboutLicenseLink": "Licence MIT",
        "AboutContactSupport": "Contacter le support",
        "AboutClose": "Fermer",
        "AboutLicenseUnavailable": "Le texte de la licence n'a pas pu être chargé. Cette application est distribuée sous licence MIT.",
        "SupportDisclosure": "Contacter le support charge le site web de Green Yoga (greenyogainc.com) dans cette fenêtre. Une connexion internet est nécessaire, et la politique de confidentialité du site de Green Yoga s'applique à toute information que vous transmettez.",
        "SupportLoadButton": "Charger la page de support",
        "SupportOpenInBrowser": "Ouvrir dans le navigateur web",
        "SupportEmail": "Contacter le support par e-mail",
        "SupportRetry": "Réessayer",
        "SupportLoading": "Chargement de la page de support…",
        "SupportLoadFailed": "La page de support n'a pas pu être chargée. Vérifiez votre connexion internet et réessayez, ou utilisez l'une des options ci-dessous.",
        "SupportBack": "Retour",
        "ContinuousSectionTitleFormat": "Section {0}",
        "PageBoxName": "Numéro de chapitre",
        "MetadataFormat": DASH_FMT,
        "FindNext": "Suivant", "FindPrev": "Précédent", "CloseSearch": "Fermer",
        "NoSearchResults": "Aucun résultat", "SearchResultsFormat": "{0} résultats",
        "NoReadableContent": "Ce livre ne contient aucune page lisible.",
    },
    "de": {
        "AppTitle": APP_TITLE, "MainWindowTitleFormat": DASH_FMT,
        "Open": "Öffnen…", "OpenTooltip": "EPUB öffnen (Strg+O)",
        "Facing": "Doppel", "FacingTooltip": "Doppelseiten-Ansicht (2)",
        "Single": "Einzeln", "SingleTooltip": "Einzelseite (1) – F11 für Vollbild",
        "Scroll": "Scrollen", "ScrollTooltip": "Fortlaufendes Scrollen durch Kapitel (3)",
        "PrevPageTooltip": "Vorherige Seite (Bild auf)", "NextPageTooltip": "Nächste Seite (Bild ab)",
        "FontOutTooltip": "Schrift verkleinern (Strg+-)", "FontInTooltip": "Schrift vergrößern (Strg++)",
        "Theme": "Thema", "ThemeTooltip": "Lesethema",
        "Search": "Suchen", "SearchTooltip": "Buch durchsuchen (Strg+F)", "SearchPlaceholder": "Im Buch suchen…",
        "Settings": "Einstellungen", "SettingsTooltip": "Typografie und Optionen",
        "Print": "Drucken…", "PrintTooltip": "Aktuelles Kapitel drucken (Strg+P)",
        "FullscreenTooltip": "Vollbild (F11)",
        "EmptyHint": "EPUB öffnen  (Strg+O)  —  oder Datei hier ablegen",
        "OpenSampleBook": "Beispielbuch öffnen",
        "ChapterCountFormat": COUNT_FMT, "ProgressFormat": "{0}%",
        "OpenFileDialogFilter": "EPUB-Dateien (*.epub)|*.epub", "OpenFileDialogTitle": "EPUB öffnen",
        "OpenFileErrorMessage": '„{0}" konnte nicht geöffnet werden.\n\n{1}',
        "UnhandledErrorMessage": "Unerwarteter Fehler:\n\n{0}\n\nDetails protokolliert unter:\n{1}",
        "Chapters": "Kapitel", "ChaptersTooltip": "Kapitel anzeigen oder ausblenden (F4)",
        "CloseChaptersTooltip": "Kapitel schließen", "LoadingChapters": "Kapitel werden geladen…",
        "NoChapters": "Dieses Buch hat kein Inhaltsverzeichnis.", "UntitledChapter": "Unbenanntes Kapitel",
        "ChapterLoadFailed": "Kapitel konnten nicht geladen werden.",
        "Bookmarks": "Lesezeichen", "NoBookmarks": "Noch keine Lesezeichen. Drücken Sie B, um eines hinzuzufügen.",
        "FontPublisher": "Verlagsschrift", "FontSerif": "Serif", "FontSans": "Serifenlos",
        "ThemeLight": "Hell", "ThemeSepia": "Sepia", "ThemeDark": "Dunkel",
        "LineSpacing": "Zeilenabstand", "Margins": "Ränder", "ResetText": "Textoptionen zurücksetzen",
        "About": "Über EPUB Lite Reader",
        "AboutWindowTitleFormat": "Über {0}",
        "AboutVersionFormat": "Version {0}",
        "AboutPublishedBy": "Veröffentlicht von Green Yoga Inc.",
        "AboutBrandBlurb": "Green Yoga Inc entwickelt durchdachte Software und digitale Werkzeuge für Lesen, Wohlbefinden und praktische Technologie.",
        "AboutWebsiteLink": "Green Yoga Website",
        "AboutPrivacyLink": "Datenschutzerklärung",
        "AboutLicenseLink": "MIT-Lizenz",
        "AboutContactSupport": "Support kontaktieren",
        "AboutClose": "Schließen",
        "AboutLicenseUnavailable": "Der Lizenztext konnte nicht geladen werden. Diese Anwendung wird unter der MIT-Lizenz veröffentlicht.",
        "SupportDisclosure": "\u201eSupport kontaktieren\" lädt die Green-Yoga-Website (greenyogainc.com) in diesem Fenster. Eine Internetverbindung ist erforderlich, und die Datenschutzerklärung der Green-Yoga-Website gilt für alle Angaben, die Sie übermitteln.",
        "SupportLoadButton": "Support-Seite laden",
        "SupportOpenInBrowser": "Im Webbrowser öffnen",
        "SupportEmail": "Support per E-Mail kontaktieren",
        "SupportRetry": "Erneut versuchen",
        "SupportLoading": "Support-Seite wird geladen…",
        "SupportLoadFailed": "Die Support-Seite konnte nicht geladen werden. Überprüfen Sie Ihre Internetverbindung und versuchen Sie es erneut, oder nutzen Sie eine der folgenden Optionen.",
        "SupportBack": "Zurück",
        "ContinuousSectionTitleFormat": "Abschnitt {0}",
        "PageBoxName": "Kapitelnummer",
        "MetadataFormat": DASH_FMT,
        "FindNext": "Weitersuchen", "FindPrev": "Rückwärts suchen", "CloseSearch": "Schließen",
        "NoSearchResults": "Keine Treffer", "SearchResultsFormat": "{0} Treffer",
        "NoReadableContent": "Dieses Buch enthält keine lesbaren Seiten.",
    },
    "it": {
        "AppTitle": APP_TITLE, "MainWindowTitleFormat": DASH_FMT,
        "Open": "Apri…", "OpenTooltip": "Apri un EPUB (Ctrl+O)",
        "Facing": "Doppia", "FacingTooltip": "Impaginazione a doppia pagina (2)",
        "Single": "Singola", "SingleTooltip": "Pagina singola (1) — premi F11 per lo schermo intero",
        "Scroll": "Scorri", "ScrollTooltip": "Scorrimento continuo dei capitoli (3)",
        "PrevPageTooltip": "Pagina precedente (Pagina su)", "NextPageTooltip": "Pagina successiva (Pagina giù)",
        "FontOutTooltip": "Riduci dimensione testo (Ctrl+-)", "FontInTooltip": "Aumenta dimensione testo (Ctrl++)",
        "Theme": "Tema", "ThemeTooltip": "Tema di lettura",
        "Search": "Cerca", "SearchTooltip": "Cerca nel libro (Ctrl+F)", "SearchPlaceholder": "Cerca nel libro…",
        "Settings": "Impostazioni", "SettingsTooltip": "Tipografia e opzioni",
        "Print": "Stampa…", "PrintTooltip": "Stampa il capitolo corrente (Ctrl+P)",
        "FullscreenTooltip": "Schermo intero (F11)",
        "EmptyHint": "Apri un EPUB  (Ctrl+O)  —  oppure trascina qui un file",
        "OpenSampleBook": "Apri libro di esempio",
        "ChapterCountFormat": COUNT_FMT, "ProgressFormat": "{0}%",
        "OpenFileDialogFilter": "File EPUB (*.epub)|*.epub", "OpenFileDialogTitle": "Apri EPUB",
        "OpenFileErrorMessage": 'Impossibile aprire "{0}".\n\n{1}',
        "UnhandledErrorMessage": "Errore imprevisto:\n\n{0}\n\nDettagli registrati in:\n{1}",
        "Chapters": "Capitoli", "ChaptersTooltip": "Mostra o nascondi i capitoli (F4)",
        "CloseChaptersTooltip": "Chiudi capitoli", "LoadingChapters": "Caricamento dei capitoli…",
        "NoChapters": "Questo libro non ha un sommario.", "UntitledChapter": "Capitolo senza titolo",
        "ChapterLoadFailed": "Impossibile caricare i capitoli.",
        "Bookmarks": "Segnalibri", "NoBookmarks": "Nessun segnalibro. Premi B per aggiungerne uno.",
        "FontPublisher": "Carattere dell'editore", "FontSerif": "Serif", "FontSans": "Sans-serif",
        "ThemeLight": "Chiaro", "ThemeSepia": "Seppia", "ThemeDark": "Scuro",
        "LineSpacing": "Interlinea", "Margins": "Margini", "ResetText": "Ripristina impostazioni testo",
        "About": "Informazioni su EPUB Lite Reader",
        "AboutWindowTitleFormat": "Informazioni su {0}",
        "AboutVersionFormat": "Versione {0}",
        "AboutPublishedBy": "Pubblicato da Green Yoga Inc.",
        "AboutBrandBlurb": "Green Yoga Inc crea software e strumenti digitali pensati per la lettura, il benessere e la tecnologia pratica.",
        "AboutWebsiteLink": "Sito web di Green Yoga",
        "AboutPrivacyLink": "Informativa sulla privacy",
        "AboutLicenseLink": "Licenza MIT",
        "AboutContactSupport": "Contatta il supporto",
        "AboutClose": "Chiudi",
        "AboutLicenseUnavailable": "Impossibile caricare il testo della licenza. Questa applicazione è distribuita con Licenza MIT.",
        "SupportDisclosure": "Contatta il supporto carica il sito web di Green Yoga (greenyogainc.com) all'interno di questa finestra. È necessaria una connessione internet e l'informativa sulla privacy del sito Green Yoga si applica a qualsiasi informazione inviata.",
        "SupportLoadButton": "Carica pagina di supporto",
        "SupportOpenInBrowser": "Apri nel browser web",
        "SupportEmail": "Contatta il supporto via e-mail",
        "SupportRetry": "Riprova",
        "SupportLoading": "Caricamento della pagina di supporto…",
        "SupportLoadFailed": "Impossibile caricare la pagina di supporto. Controlla la connessione internet e riprova, oppure usa una delle opzioni seguenti.",
        "SupportBack": "Indietro",
        "ContinuousSectionTitleFormat": "Sezione {0}",
        "PageBoxName": "Numero di capitolo",
        "MetadataFormat": DASH_FMT,
        "FindNext": "Trova successivo", "FindPrev": "Trova precedente", "CloseSearch": "Chiudi",
        "NoSearchResults": "Nessun risultato", "SearchResultsFormat": "{0} risultati",
        "NoReadableContent": "Questo libro non contiene pagine leggibili.",
    },
    "pt-BR": {
        "AppTitle": APP_TITLE, "MainWindowTitleFormat": DASH_FMT,
        "Open": "Abrir…", "OpenTooltip": "Abrir um EPUB (Ctrl+O)",
        "Facing": "Dupla", "FacingTooltip": "Visualização de livro em página dupla (2)",
        "Single": "Única", "SingleTooltip": "Página única (1) — pressione F11 para tela cheia",
        "Scroll": "Contínuo", "ScrollTooltip": "Rolagem contínua de capítulos (3)",
        "PrevPageTooltip": "Página anterior (Page Up)", "NextPageTooltip": "Próxima página (Page Down)",
        "FontOutTooltip": "Diminuir tamanho do texto (Ctrl+-)", "FontInTooltip": "Aumentar tamanho do texto (Ctrl++)",
        "Theme": "Tema", "ThemeTooltip": "Tema de leitura",
        "Search": "Pesquisar", "SearchTooltip": "Pesquisar no livro (Ctrl+F)", "SearchPlaceholder": "Pesquisar no livro…",
        "Settings": "Configurações", "SettingsTooltip": "Tipografia e opções",
        "Print": "Imprimir…", "PrintTooltip": "Imprimir capítulo atual (Ctrl+P)",
        "FullscreenTooltip": "Tela cheia (F11)",
        "EmptyHint": "Abra um EPUB  (Ctrl+O)  —  ou solte um arquivo aqui",
        "OpenSampleBook": "Abrir livro de exemplo",
        "ChapterCountFormat": COUNT_FMT, "ProgressFormat": "{0}%",
        "OpenFileDialogFilter": "Arquivos EPUB (*.epub)|*.epub", "OpenFileDialogTitle": "Abrir EPUB",
        "OpenFileErrorMessage": 'Não foi possível abrir "{0}".\n\n{1}',
        "UnhandledErrorMessage": "Erro inesperado:\n\n{0}\n\nDetalhes registrados em:\n{1}",
        "Chapters": "Capítulos", "ChaptersTooltip": "Mostrar ou ocultar os capítulos (F4)",
        "CloseChaptersTooltip": "Fechar capítulos", "LoadingChapters": "Carregando capítulos…",
        "NoChapters": "Este livro não tem sumário.", "UntitledChapter": "Capítulo sem título",
        "ChapterLoadFailed": "Não foi possível carregar os capítulos.",
        "Bookmarks": "Marcadores", "NoBookmarks": "Ainda não há marcadores. Pressione B para adicionar um.",
        "FontPublisher": "Fonte da editora", "FontSerif": "Serif", "FontSans": "Sans-serif",
        "ThemeLight": "Claro", "ThemeSepia": "Sépia", "ThemeDark": "Escuro",
        "LineSpacing": "Espaçamento entre linhas", "Margins": "Margens", "ResetText": "Redefinir configurações de texto",
        "About": "Sobre o EPUB Lite Reader",
        "AboutWindowTitleFormat": "Sobre o {0}",
        "AboutVersionFormat": "Versão {0}",
        "AboutPublishedBy": "Publicado pela Green Yoga Inc.",
        "AboutBrandBlurb": "A Green Yoga Inc cria softwares e ferramentas digitais pensados para leitura, bem-estar e tecnologia prática.",
        "AboutWebsiteLink": "Site da Green Yoga",
        "AboutPrivacyLink": "Política de privacidade",
        "AboutLicenseLink": "Licença MIT",
        "AboutContactSupport": "Contatar o suporte",
        "AboutClose": "Fechar",
        "AboutLicenseUnavailable": "Não foi possível carregar o texto da licença. Este aplicativo é distribuído sob a Licença MIT.",
        "SupportDisclosure": "Contatar o suporte carrega o site da Green Yoga (greenyogainc.com) dentro desta janela. É necessária conexão com a internet, e a política de privacidade do site da Green Yoga se aplica a qualquer informação que você enviar.",
        "SupportLoadButton": "Carregar página de suporte",
        "SupportOpenInBrowser": "Abrir no navegador",
        "SupportEmail": "Contatar o suporte por e-mail",
        "SupportRetry": "Tentar novamente",
        "SupportLoading": "Carregando página de suporte…",
        "SupportLoadFailed": "Não foi possível carregar a página de suporte. Verifique sua conexão com a internet e tente novamente, ou use uma das opções abaixo.",
        "SupportBack": "Voltar",
        "ContinuousSectionTitleFormat": "Seção {0}",
        "PageBoxName": "Número do capítulo",
        "MetadataFormat": DASH_FMT,
        "FindNext": "Buscar próxima", "FindPrev": "Buscar anterior", "CloseSearch": "Fechar",
        "NoSearchResults": "Nenhum resultado", "SearchResultsFormat": "{0} resultados",
        "NoReadableContent": "Este livro não tem páginas legíveis.",
    },
    "ja": {
        "AppTitle": APP_TITLE, "MainWindowTitleFormat": DASH_FMT,
        "Open": "開く…", "OpenTooltip": "EPUBを開く (Ctrl+O)",
        "Facing": "見開き", "FacingTooltip": "見開きページ表示 (2)",
        "Single": "単一", "SingleTooltip": "単一ページ (1) — F11キーで全画面表示",
        "Scroll": "スクロール", "ScrollTooltip": "章を連続スクロール (3)",
        "PrevPageTooltip": "前のページ (Page Up)", "NextPageTooltip": "次のページ (Page Down)",
        "FontOutTooltip": "文字を縮小 (Ctrl+-)", "FontInTooltip": "文字を拡大 (Ctrl++)",
        "Theme": "テーマ", "ThemeTooltip": "読書テーマ",
        "Search": "検索", "SearchTooltip": "本を検索 (Ctrl+F)", "SearchPlaceholder": "本の中を検索…",
        "Settings": "設定", "SettingsTooltip": "文字組みとオプション",
        "Print": "印刷…", "PrintTooltip": "現在の章を印刷 (Ctrl+P)",
        "FullscreenTooltip": "全画面表示 (F11)",
        "EmptyHint": "EPUBを開く (Ctrl+O)  —  またはファイルをここにドロップ",
        "OpenSampleBook": "サンプル本を開く",
        "ChapterCountFormat": COUNT_FMT, "ProgressFormat": "{0}%",
        "OpenFileDialogFilter": "EPUBファイル (*.epub)|*.epub", "OpenFileDialogTitle": "EPUBを開く",
        "OpenFileErrorMessage": '"{0}" を開けませんでした。\n\n{1}',
        "UnhandledErrorMessage": "予期しないエラー:\n\n{0}\n\n詳細はログに記録されました:\n{1}",
        "Chapters": "章", "ChaptersTooltip": "章を表示または非表示にします (F4)",
        "CloseChaptersTooltip": "章を閉じる", "LoadingChapters": "章を読み込んでいます…",
        "NoChapters": "この本には目次がありません。", "UntitledChapter": "無題の章",
        "ChapterLoadFailed": "章を読み込めませんでした。",
        "Bookmarks": "しおり", "NoBookmarks": "しおりはまだありません。Bキーで追加できます。",
        "FontPublisher": "出版社指定のフォント", "FontSerif": "セリフ体", "FontSans": "サンセリフ体",
        "ThemeLight": "ライト", "ThemeSepia": "セピア", "ThemeDark": "ダーク",
        "LineSpacing": "行間", "Margins": "余白", "ResetText": "テキスト設定をリセット",
        "About": "EPUB Lite Readerについて",
        "AboutWindowTitleFormat": "{0} について",
        "AboutVersionFormat": "バージョン {0}",
        "AboutPublishedBy": "Green Yoga Inc. 発行",
        "AboutBrandBlurb": "Green Yoga Inc は、読書、ウェルネス、実用的なテクノロジーのための工夫を凝らしたソフトウェアとデジタルツールを開発しています。",
        "AboutWebsiteLink": "Green Yoga ウェブサイト",
        "AboutPrivacyLink": "プライバシーポリシー",
        "AboutLicenseLink": "MITライセンス",
        "AboutContactSupport": "サポートに問い合わせる",
        "AboutClose": "閉じる",
        "AboutLicenseUnavailable": "ライセンス文を読み込めませんでした。このアプリケーションはMITライセンスの下で公開されています。",
        "SupportDisclosure": "「サポートに問い合わせる」を選択すると、このウィンドウ内にGreen Yogaのウェブサイト (greenyogainc.com) が読み込まれます。インターネット接続が必要であり、送信する情報にはGreen Yogaウェブサイトのプライバシーポリシーが適用されます。",
        "SupportLoadButton": "サポートページを読み込む",
        "SupportOpenInBrowser": "ウェブブラウザで開く",
        "SupportEmail": "メールでサポートに問い合わせる",
        "SupportRetry": "再試行",
        "SupportLoading": "サポートページを読み込んでいます…",
        "SupportLoadFailed": "サポートページを読み込めませんでした。インターネット接続を確認して再試行するか、以下のいずれかのオプションをご利用ください。",
        "SupportBack": "戻る",
        "ContinuousSectionTitleFormat": "セクション {0}",
        "PageBoxName": "章番号",
        "MetadataFormat": DASH_FMT,
        "FindNext": "次を検索", "FindPrev": "前を検索", "CloseSearch": "閉じる",
        "NoSearchResults": "一致なし", "SearchResultsFormat": "{0} 件一致",
        "NoReadableContent": "この本には表示できるページがありません。",
    },
    "ko": {
        "AppTitle": APP_TITLE, "MainWindowTitleFormat": DASH_FMT,
        "Open": "열기…", "OpenTooltip": "EPUB 열기 (Ctrl+O)",
        "Facing": "마주보기", "FacingTooltip": "마주보는 페이지 보기 (2)",
        "Single": "단일", "SingleTooltip": "단일 페이지 (1) — F11 키로 전체 화면",
        "Scroll": "스크롤", "ScrollTooltip": "장 연속 스크롤 (3)",
        "PrevPageTooltip": "이전 페이지 (Page Up)", "NextPageTooltip": "다음 페이지 (Page Down)",
        "FontOutTooltip": "글자 크기 축소 (Ctrl+-)", "FontInTooltip": "글자 크기 확대 (Ctrl++)",
        "Theme": "테마", "ThemeTooltip": "읽기 테마",
        "Search": "검색", "SearchTooltip": "책 검색 (Ctrl+F)", "SearchPlaceholder": "책에서 찾기…",
        "Settings": "설정", "SettingsTooltip": "타이포그래피 및 옵션",
        "Print": "인쇄…", "PrintTooltip": "현재 장 인쇄 (Ctrl+P)",
        "FullscreenTooltip": "전체 화면 (F11)",
        "EmptyHint": "EPUB 열기  (Ctrl+O)  —  또는 파일을 여기로 끌어다 놓으세요",
        "OpenSampleBook": "샘플 도서 열기",
        "ChapterCountFormat": COUNT_FMT, "ProgressFormat": "{0}%",
        "OpenFileDialogFilter": "EPUB 파일 (*.epub)|*.epub", "OpenFileDialogTitle": "EPUB 열기",
        "OpenFileErrorMessage": '"{0}"을(를) 열 수 없습니다.\n\n{1}',
        "UnhandledErrorMessage": "예기치 않은 오류:\n\n{0}\n\n자세한 내용은 다음 위치에 기록되었습니다:\n{1}",
        "Chapters": "장", "ChaptersTooltip": "장 표시 또는 숨기기 (F4)",
        "CloseChaptersTooltip": "장 닫기", "LoadingChapters": "장을 불러오는 중…",
        "NoChapters": "이 책에는 목차가 없습니다.", "UntitledChapter": "제목 없는 장",
        "ChapterLoadFailed": "장을 불러올 수 없습니다.",
        "Bookmarks": "책갈피", "NoBookmarks": "아직 책갈피가 없습니다. B 키를 눌러 추가하세요.",
        "FontPublisher": "출판사 글꼴", "FontSerif": "세리프", "FontSans": "산세리프",
        "ThemeLight": "라이트", "ThemeSepia": "세피아", "ThemeDark": "다크",
        "LineSpacing": "줄 간격", "Margins": "여백", "ResetText": "텍스트 설정 재설정",
        "About": "EPUB Lite Reader 정보",
        "AboutWindowTitleFormat": "{0} 정보",
        "AboutVersionFormat": "버전 {0}",
        "AboutPublishedBy": "Green Yoga Inc. 제공",
        "AboutBrandBlurb": "Green Yoga Inc는 독서, 웰빙, 실용적인 기술을 위한 세심한 소프트웨어와 디지털 도구를 만듭니다.",
        "AboutWebsiteLink": "Green Yoga 웹사이트",
        "AboutPrivacyLink": "개인정보 처리방침",
        "AboutLicenseLink": "MIT 라이선스",
        "AboutContactSupport": "지원팀에 문의",
        "AboutClose": "닫기",
        "AboutLicenseUnavailable": "라이선스 텍스트를 불러올 수 없습니다. 이 애플리케이션은 MIT 라이선스에 따라 배포됩니다.",
        "SupportDisclosure": "지원팀에 문의를 선택하면 이 창 안에서 Green Yoga 웹사이트(greenyogainc.com)를 불러옵니다. 인터넷 연결이 필요하며, 제출하는 모든 정보에는 Green Yoga 웹사이트의 개인정보 처리방침이 적용됩니다.",
        "SupportLoadButton": "지원 페이지 불러오기",
        "SupportOpenInBrowser": "웹 브라우저에서 열기",
        "SupportEmail": "이메일로 지원팀에 문의",
        "SupportRetry": "다시 시도",
        "SupportLoading": "지원 페이지를 불러오는 중…",
        "SupportLoadFailed": "지원 페이지를 불러올 수 없습니다. 인터넷 연결을 확인한 후 다시 시도하거나 아래 옵션 중 하나를 사용하세요.",
        "SupportBack": "뒤로",
        "ContinuousSectionTitleFormat": "섹션 {0}",
        "PageBoxName": "장 번호",
        "MetadataFormat": DASH_FMT,
        "FindNext": "다음 찾기", "FindPrev": "이전 찾기", "CloseSearch": "닫기",
        "NoSearchResults": "일치하는 항목 없음", "SearchResultsFormat": "{0}개 일치",
        "NoReadableContent": "이 책에는 읽을 수 있는 페이지가 없습니다.",
    },
    "zh-Hans": {
        "AppTitle": APP_TITLE, "MainWindowTitleFormat": DASH_FMT,
        "Open": "打开…", "OpenTooltip": "打开 EPUB (Ctrl+O)",
        "Facing": "双页", "FacingTooltip": "双页对照版式 (2)",
        "Single": "单页", "SingleTooltip": "单页 (1) — 按 F11 全屏",
        "Scroll": "滚动", "ScrollTooltip": "连续滚动章节 (3)",
        "PrevPageTooltip": "上一页 (Page Up)", "NextPageTooltip": "下一页 (Page Down)",
        "FontOutTooltip": "缩小文字 (Ctrl+-)", "FontInTooltip": "放大文字 (Ctrl++)",
        "Theme": "主题", "ThemeTooltip": "阅读主题",
        "Search": "搜索", "SearchTooltip": "搜索书籍 (Ctrl+F)", "SearchPlaceholder": "在书中查找…",
        "Settings": "设置", "SettingsTooltip": "排版和选项",
        "Print": "打印…", "PrintTooltip": "打印当前章节 (Ctrl+P)",
        "FullscreenTooltip": "全屏 (F11)",
        "EmptyHint": "打开 EPUB  (Ctrl+O)  — 或将文件拖到此处",
        "OpenSampleBook": "打开示例书籍",
        "ChapterCountFormat": COUNT_FMT, "ProgressFormat": "{0}%",
        "OpenFileDialogFilter": "EPUB 文件 (*.epub)|*.epub", "OpenFileDialogTitle": "打开 EPUB",
        "OpenFileErrorMessage": '无法打开"{0}"。\n\n{1}',
        "UnhandledErrorMessage": "意外错误:\n\n{0}\n\n详细信息已记录到:\n{1}",
        "Chapters": "章节", "ChaptersTooltip": "显示或隐藏章节 (F4)",
        "CloseChaptersTooltip": "关闭章节", "LoadingChapters": "正在加载章节…",
        "NoChapters": "此书没有目录。", "UntitledChapter": "无标题章节",
        "ChapterLoadFailed": "无法加载章节。",
        "Bookmarks": "书签", "NoBookmarks": "还没有书签。按 B 添加一个。",
        "FontPublisher": "出版商字体", "FontSerif": "衬线体", "FontSans": "无衬线体",
        "ThemeLight": "浅色", "ThemeSepia": "护眼", "ThemeDark": "深色",
        "LineSpacing": "行距", "Margins": "页边距", "ResetText": "重置文字设置",
        "About": "关于 EPUB Lite Reader",
        "AboutWindowTitleFormat": "关于 {0}",
        "AboutVersionFormat": "版本 {0}",
        "AboutPublishedBy": "由 Green Yoga Inc. 出品",
        "AboutBrandBlurb": "Green Yoga Inc 打造用心设计的软件与数字工具，专注于阅读、身心健康与实用科技。",
        "AboutWebsiteLink": "Green Yoga 官网",
        "AboutPrivacyLink": "隐私政策",
        "AboutLicenseLink": "MIT 许可证",
        "AboutContactSupport": "联系支持",
        "AboutClose": "关闭",
        "AboutLicenseUnavailable": "无法加载许可证文本。本应用程序根据 MIT 许可证发布。",
        "SupportDisclosure": "点击\"联系支持\"会在此窗口内加载 Green Yoga 官网 (greenyogainc.com)。需要联网，且您提交的任何信息均适用 Green Yoga 官网的隐私政策。",
        "SupportLoadButton": "加载支持页面",
        "SupportOpenInBrowser": "在网页浏览器中打开",
        "SupportEmail": "通过电子邮件联系支持",
        "SupportRetry": "重试",
        "SupportLoading": "正在加载支持页面…",
        "SupportLoadFailed": "无法加载支持页面。请检查您的网络连接并重试，或使用以下选项之一。",
        "SupportBack": "返回",
        "ContinuousSectionTitleFormat": "第 {0} 节",
        "PageBoxName": "章节编号",
        "MetadataFormat": DASH_FMT,
        "FindNext": "查找下一个", "FindPrev": "查找上一个", "CloseSearch": "关闭",
        "NoSearchResults": "无匹配项", "SearchResultsFormat": "{0} 处匹配",
        "NoReadableContent": "此书没有可阅读的页面。",
    },
    "zh-Hant": {
        "AppTitle": APP_TITLE, "MainWindowTitleFormat": DASH_FMT,
        "Open": "開啟…", "OpenTooltip": "開啟 EPUB (Ctrl+O)",
        "Facing": "雙頁", "FacingTooltip": "雙頁對照版面 (2)",
        "Single": "單頁", "SingleTooltip": "單頁 (1) — 按 F11 全螢幕",
        "Scroll": "捲動", "ScrollTooltip": "連續捲動章節 (3)",
        "PrevPageTooltip": "上一頁 (Page Up)", "NextPageTooltip": "下一頁 (Page Down)",
        "FontOutTooltip": "縮小文字 (Ctrl+-)", "FontInTooltip": "放大文字 (Ctrl++)",
        "Theme": "主題", "ThemeTooltip": "閱讀主題",
        "Search": "搜尋", "SearchTooltip": "搜尋書籍 (Ctrl+F)", "SearchPlaceholder": "在書中尋找…",
        "Settings": "設定", "SettingsTooltip": "排版與選項",
        "Print": "列印…", "PrintTooltip": "列印目前章節 (Ctrl+P)",
        "FullscreenTooltip": "全螢幕 (F11)",
        "EmptyHint": "開啟 EPUB  (Ctrl+O)  — 或將檔案拖曳至此",
        "OpenSampleBook": "開啟範例書籍",
        "ChapterCountFormat": COUNT_FMT, "ProgressFormat": "{0}%",
        "OpenFileDialogFilter": "EPUB 檔案 (*.epub)|*.epub", "OpenFileDialogTitle": "開啟 EPUB",
        "OpenFileErrorMessage": "無法開啟「{0}」。\n\n{1}",
        "UnhandledErrorMessage": "未預期的錯誤:\n\n{0}\n\n詳細資訊已記錄至:\n{1}",
        "Chapters": "章節", "ChaptersTooltip": "顯示或隱藏章節 (F4)",
        "CloseChaptersTooltip": "關閉章節", "LoadingChapters": "正在載入章節…",
        "NoChapters": "此書沒有目錄。", "UntitledChapter": "無標題章節",
        "ChapterLoadFailed": "無法載入章節。",
        "Bookmarks": "書籤", "NoBookmarks": "尚無書籤。按 B 新增一個。",
        "FontPublisher": "出版商字型", "FontSerif": "襯線體", "FontSans": "無襯線體",
        "ThemeLight": "淺色", "ThemeSepia": "護眼", "ThemeDark": "深色",
        "LineSpacing": "行距", "Margins": "邊界", "ResetText": "重設文字設定",
        "About": "關於 EPUB Lite Reader",
        "AboutWindowTitleFormat": "關於 {0}",
        "AboutVersionFormat": "版本 {0}",
        "AboutPublishedBy": "由 Green Yoga Inc. 出品",
        "AboutBrandBlurb": "Green Yoga Inc 打造用心設計的軟體與數位工具，專注於閱讀、身心健康與實用科技。",
        "AboutWebsiteLink": "Green Yoga 官方網站",
        "AboutPrivacyLink": "隱私權政策",
        "AboutLicenseLink": "MIT 授權",
        "AboutContactSupport": "聯絡支援",
        "AboutClose": "關閉",
        "AboutLicenseUnavailable": "無法載入授權條款文字。本應用程式依 MIT 授權發布。",
        "SupportDisclosure": "點選「聯絡支援」會在此視窗內載入 Green Yoga 官方網站 (greenyogainc.com)。需要網際網路連線，且您提交的任何資訊均適用 Green Yoga 網站的隱私權政策。",
        "SupportLoadButton": "載入支援頁面",
        "SupportOpenInBrowser": "在網頁瀏覽器中開啟",
        "SupportEmail": "透過電子郵件聯絡支援",
        "SupportRetry": "重試",
        "SupportLoading": "正在載入支援頁面…",
        "SupportLoadFailed": "無法載入支援頁面。請檢查您的網際網路連線並重試，或使用下列選項之一。",
        "SupportBack": "返回",
        "ContinuousSectionTitleFormat": "第 {0} 節",
        "PageBoxName": "章節編號",
        "MetadataFormat": DASH_FMT,
        "FindNext": "尋找下一個", "FindPrev": "尋找上一個", "CloseSearch": "關閉",
        "NoSearchResults": "沒有相符項目", "SearchResultsFormat": "{0} 個相符項目",
        "NoReadableContent": "此書沒有可閱讀的頁面。",
    },
    "ru": {
        "AppTitle": APP_TITLE, "MainWindowTitleFormat": DASH_FMT,
        "Open": "Открыть…", "OpenTooltip": "Открыть EPUB (Ctrl+O)",
        "Facing": "Разворот", "FacingTooltip": "Книжный разворот (2)",
        "Single": "Одна", "SingleTooltip": "Одна страница (1) — F11 для полноэкранного режима",
        "Scroll": "Прокрутка", "ScrollTooltip": "Непрерывная прокрутка глав (3)",
        "PrevPageTooltip": "Предыдущая страница (Page Up)", "NextPageTooltip": "Следующая страница (Page Down)",
        "FontOutTooltip": "Уменьшить текст (Ctrl+-)", "FontInTooltip": "Увеличить текст (Ctrl++)",
        "Theme": "Тема", "ThemeTooltip": "Тема чтения",
        "Search": "Поиск", "SearchTooltip": "Поиск по книге (Ctrl+F)", "SearchPlaceholder": "Поиск в книге…",
        "Settings": "Настройки", "SettingsTooltip": "Типографика и параметры",
        "Print": "Печать…", "PrintTooltip": "Печать текущей главы (Ctrl+P)",
        "FullscreenTooltip": "Полноэкранный режим (F11)",
        "EmptyHint": "Откройте EPUB (Ctrl+O)  —  или перетащите файл сюда",
        "OpenSampleBook": "Открыть пример книги",
        "ChapterCountFormat": COUNT_FMT, "ProgressFormat": "{0}%",
        "OpenFileDialogFilter": "Файлы EPUB (*.epub)|*.epub", "OpenFileDialogTitle": "Открыть EPUB",
        "OpenFileErrorMessage": "Не удалось открыть «{0}».\n\n{1}",
        "UnhandledErrorMessage": "Непредвиденная ошибка:\n\n{0}\n\nПодробности записаны в:\n{1}",
        "Chapters": "Главы", "ChaptersTooltip": "Показать или скрыть главы (F4)",
        "CloseChaptersTooltip": "Закрыть главы", "LoadingChapters": "Загрузка глав…",
        "NoChapters": "В этой книге нет оглавления.", "UntitledChapter": "Глава без названия",
        "ChapterLoadFailed": "Не удалось загрузить главы.",
        "Bookmarks": "Закладки", "NoBookmarks": "Закладок пока нет. Нажмите B, чтобы добавить.",
        "FontPublisher": "Шрифт издателя", "FontSerif": "С засечками", "FontSans": "Без засечек",
        "ThemeLight": "Светлая", "ThemeSepia": "Сепия", "ThemeDark": "Тёмная",
        "LineSpacing": "Межстрочный интервал", "Margins": "Поля", "ResetText": "Сбросить настройки текста",
        "About": "О программе EPUB Lite Reader",
        "AboutWindowTitleFormat": "О программе {0}",
        "AboutVersionFormat": "Версия {0}",
        "AboutPublishedBy": "Издатель — Green Yoga Inc.",
        "AboutBrandBlurb": "Green Yoga Inc создаёт продуманное программное обеспечение и цифровые инструменты для чтения, благополучия и практичных технологий.",
        "AboutWebsiteLink": "Веб-сайт Green Yoga",
        "AboutPrivacyLink": "Политика конфиденциальности",
        "AboutLicenseLink": "Лицензия MIT",
        "AboutContactSupport": "Связаться со службой поддержки",
        "AboutClose": "Закрыть",
        "AboutLicenseUnavailable": "Не удалось загрузить текст лицензии. Это приложение распространяется по лицензии MIT.",
        "SupportDisclosure": "При выборе «Связаться со службой поддержки» в этом окне загружается веб-сайт Green Yoga (greenyogainc.com). Требуется подключение к интернету, и к любой отправляемой вами информации применяется политика конфиденциальности веб-сайта Green Yoga.",
        "SupportLoadButton": "Загрузить страницу поддержки",
        "SupportOpenInBrowser": "Открыть в веб-браузере",
        "SupportEmail": "Написать в службу поддержки",
        "SupportRetry": "Повторить",
        "SupportLoading": "Загрузка страницы поддержки…",
        "SupportLoadFailed": "Не удалось загрузить страницу поддержки. Проверьте подключение к интернету и повторите попытку либо воспользуйтесь одним из вариантов ниже.",
        "SupportBack": "Назад",
        "ContinuousSectionTitleFormat": "Раздел {0}",
        "PageBoxName": "Номер главы",
        "MetadataFormat": DASH_FMT,
        "FindNext": "Найти далее", "FindPrev": "Найти ранее", "CloseSearch": "Закрыть",
        "NoSearchResults": "Совпадений нет", "SearchResultsFormat": "Совпадений: {0}",
        "NoReadableContent": "В этой книге нет страниц для чтения.",
    },
    "uk": {
        "AppTitle": APP_TITLE, "MainWindowTitleFormat": DASH_FMT,
        "Open": "Відкрити…", "OpenTooltip": "Відкрити EPUB (Ctrl+O)",
        "Facing": "Розворот", "FacingTooltip": "Книжковий розворот (2)",
        "Single": "Одна", "SingleTooltip": "Одна сторінка (1) — натисніть F11 для повноекранного режиму",
        "Scroll": "Прокрутка", "ScrollTooltip": "Безперервна прокрутка розділів (3)",
        "PrevPageTooltip": "Попередня сторінка (Page Up)", "NextPageTooltip": "Наступна сторінка (Page Down)",
        "FontOutTooltip": "Зменшити текст (Ctrl+-)", "FontInTooltip": "Збільшити текст (Ctrl++)",
        "Theme": "Тема", "ThemeTooltip": "Тема читання",
        "Search": "Пошук", "SearchTooltip": "Пошук у книзі (Ctrl+F)", "SearchPlaceholder": "Пошук у книзі…",
        "Settings": "Налаштування", "SettingsTooltip": "Типографіка та параметри",
        "Print": "Друк…", "PrintTooltip": "Друк поточного розділу (Ctrl+P)",
        "FullscreenTooltip": "Повноекранний режим (F11)",
        "EmptyHint": "Відкрийте EPUB (Ctrl+O)  —  або перетягніть файл сюди",
        "OpenSampleBook": "Відкрити приклад книги",
        "ChapterCountFormat": COUNT_FMT, "ProgressFormat": "{0}%",
        "OpenFileDialogFilter": "Файли EPUB (*.epub)|*.epub", "OpenFileDialogTitle": "Відкрити EPUB",
        "OpenFileErrorMessage": "Не вдалося відкрити «{0}».\n\n{1}",
        "UnhandledErrorMessage": "Неочікувана помилка:\n\n{0}\n\nПодробиці записано до:\n{1}",
        "Chapters": "Розділи", "ChaptersTooltip": "Показати або приховати розділи (F4)",
        "CloseChaptersTooltip": "Закрити розділи", "LoadingChapters": "Завантаження розділів…",
        "NoChapters": "У цій книзі немає змісту.", "UntitledChapter": "Розділ без назви",
        "ChapterLoadFailed": "Не вдалося завантажити розділи.",
        "Bookmarks": "Закладки", "NoBookmarks": "Закладок ще немає. Натисніть B, щоб додати.",
        "FontPublisher": "Шрифт видавця", "FontSerif": "Із засічками", "FontSans": "Без засічок",
        "ThemeLight": "Світла", "ThemeSepia": "Сепія", "ThemeDark": "Темна",
        "LineSpacing": "Міжрядковий інтервал", "Margins": "Поля", "ResetText": "Скинути налаштування тексту",
        "About": "Про EPUB Lite Reader",
        "AboutWindowTitleFormat": "Про {0}",
        "AboutVersionFormat": "Версія {0}",
        "AboutPublishedBy": "Видавець — Green Yoga Inc.",
        "AboutBrandBlurb": "Green Yoga Inc створює продумане програмне забезпечення та цифрові інструменти для читання, добробуту та практичних технологій.",
        "AboutWebsiteLink": "Веб-сайт Green Yoga",
        "AboutPrivacyLink": "Політика конфіденційності",
        "AboutLicenseLink": "Ліцензія MIT",
        "AboutContactSupport": "Звернутися до підтримки",
        "AboutClose": "Закрити",
        "AboutLicenseUnavailable": "Не вдалося завантажити текст ліцензії. Ця програма розповсюджується за ліцензією MIT.",
        "SupportDisclosure": "«Звернутися до підтримки» завантажує веб-сайт Green Yoga (greenyogainc.com) у цьому вікні. Потрібне підключення до інтернету, і до будь-якої інформації, яку ви надсилаєте, застосовується політика конфіденційності веб-сайту Green Yoga.",
        "SupportLoadButton": "Завантажити сторінку підтримки",
        "SupportOpenInBrowser": "Відкрити у веб-браузері",
        "SupportEmail": "Написати в підтримку",
        "SupportRetry": "Повторити",
        "SupportLoading": "Завантаження сторінки підтримки…",
        "SupportLoadFailed": "Не вдалося завантажити сторінку підтримки. Перевірте підключення до інтернету й спробуйте ще раз або скористайтеся одним із варіантів нижче.",
        "SupportBack": "Назад",
        "ContinuousSectionTitleFormat": "Секція {0}",
        "PageBoxName": "Номер розділу",
        "MetadataFormat": DASH_FMT,
        "FindNext": "Знайти далі", "FindPrev": "Знайти раніше", "CloseSearch": "Закрити",
        "NoSearchResults": "Немає збігів", "SearchResultsFormat": "Збігів: {0}",
        "NoReadableContent": "У цій книзі немає сторінок для читання.",
    },
    "ar": {
        "AppTitle": APP_TITLE, "MainWindowTitleFormat": DASH_FMT,
        "Open": "فتح…", "OpenTooltip": "فتح ملف EPUB (Ctrl+O)",
        "Facing": "صفحتان", "FacingTooltip": "تخطيط كتاب بصفحتين (2)",
        "Single": "صفحة واحدة", "SingleTooltip": "صفحة واحدة (1) — اضغط F11 لملء الشاشة",
        "Scroll": "تمرير", "ScrollTooltip": "تمرير متواصل للفصول (3)",
        "PrevPageTooltip": "الصفحة السابقة (Page Up)", "NextPageTooltip": "الصفحة التالية (Page Down)",
        "FontOutTooltip": "تصغير حجم النص (Ctrl+-)", "FontInTooltip": "تكبير حجم النص (Ctrl++)",
        "Theme": "المظهر", "ThemeTooltip": "مظهر القراءة",
        "Search": "بحث", "SearchTooltip": "البحث في الكتاب (Ctrl+F)", "SearchPlaceholder": "البحث في الكتاب…",
        "Settings": "الإعدادات", "SettingsTooltip": "التنسيق الطباعي والخيارات",
        "Print": "طباعة…", "PrintTooltip": "طباعة الفصل الحالي (Ctrl+P)",
        "FullscreenTooltip": "ملء الشاشة (F11)",
        "EmptyHint": "افتح ملف EPUB (Ctrl+O)  —  أو اسحب ملفًا إلى هنا",
        "OpenSampleBook": "فتح كتاب نموذجي",
        "ChapterCountFormat": COUNT_FMT, "ProgressFormat": "{0}%",
        "OpenFileDialogFilter": "ملفات EPUB (*.epub)|*.epub", "OpenFileDialogTitle": "فتح ملف EPUB",
        "OpenFileErrorMessage": 'تعذّر فتح "{0}".\n\n{1}',
        "UnhandledErrorMessage": "خطأ غير متوقع:\n\n{0}\n\nتم تسجيل التفاصيل في:\n{1}",
        "Chapters": "الفصول", "ChaptersTooltip": "إظهار الفصول أو إخفاؤها (F4)",
        "CloseChaptersTooltip": "إغلاق الفصول", "LoadingChapters": "جارٍ تحميل الفصول…",
        "NoChapters": "لا يحتوي هذا الكتاب على فهرس محتويات.", "UntitledChapter": "فصل بلا عنوان",
        "ChapterLoadFailed": "تعذر تحميل الفصول.",
        "Bookmarks": "الإشارات المرجعية", "NoBookmarks": "لا توجد إشارات مرجعية بعد. اضغط B لإضافة واحدة.",
        "FontPublisher": "خط الناشر", "FontSerif": "بأطراف زخرفية", "FontSans": "بلا أطراف زخرفية",
        "ThemeLight": "فاتح", "ThemeSepia": "بني داكن", "ThemeDark": "داكن",
        "LineSpacing": "تباعد الأسطر", "Margins": "الهوامش", "ResetText": "إعادة ضبط إعدادات النص",
        "About": "حول EPUB Lite Reader",
        "AboutWindowTitleFormat": "حول {0}",
        "AboutVersionFormat": "الإصدار {0}",
        "AboutPublishedBy": "نشرته شركة Green Yoga Inc.",
        "AboutBrandBlurb": "تبتكر شركة Green Yoga Inc برمجيات وأدوات رقمية مدروسة للقراءة والعافية والتقنية العملية.",
        "AboutWebsiteLink": "موقع Green Yoga الإلكتروني",
        "AboutPrivacyLink": "سياسة الخصوصية",
        "AboutLicenseLink": "رخصة MIT",
        "AboutContactSupport": "التواصل مع الدعم",
        "AboutClose": "إغلاق",
        "AboutLicenseUnavailable": "تعذّر تحميل نص الترخيص. يصدر هذا التطبيق بموجب رخصة MIT.",
        "SupportDisclosure": "يؤدي التواصل مع الدعم إلى تحميل موقع Green Yoga الإلكتروني (greenyogainc.com) داخل هذه النافذة. يلزم توفر اتصال بالإنترنت، وتنطبق سياسة خصوصية موقع Green Yoga على أي معلومات ترسلها.",
        "SupportLoadButton": "تحميل صفحة الدعم",
        "SupportOpenInBrowser": "فتح في متصفح الويب",
        "SupportEmail": "التواصل مع الدعم عبر البريد الإلكتروني",
        "SupportRetry": "إعادة المحاولة",
        "SupportLoading": "جارٍ تحميل صفحة الدعم…",
        "SupportLoadFailed": "تعذّر تحميل صفحة الدعم. تحقق من اتصالك بالإنترنت وحاول مرة أخرى، أو استخدم أحد الخيارات أدناه.",
        "SupportBack": "رجوع",
        "ContinuousSectionTitleFormat": "القسم {0}",
        "PageBoxName": "رقم الفصل",
        "MetadataFormat": DASH_FMT,
        "FindNext": "البحث عن التالي", "FindPrev": "البحث عن السابق", "CloseSearch": "إغلاق",
        "NoSearchResults": "لا توجد نتائج", "SearchResultsFormat": "{0} نتيجة مطابقة",
        "NoReadableContent": "لا يحتوي هذا الكتاب على صفحات قابلة للقراءة.",
    },
}
# European Portuguese: same base as pt-BR, overriding the classic PT-PT vs
# PT-BR markers (ficheiro/arquivo, ecrã/tela, definições/configurações,
# "a carregar"/"carregando", "prima"/"pressione").
TRANSLATIONS["pt"] = {
    **TRANSLATIONS["pt-BR"],
    "SingleTooltip": "Página única (1) — prima F11 para ecrã inteiro",
    "FullscreenTooltip": "Ecrã inteiro (F11)",
    "EmptyHint": "Abra um EPUB  (Ctrl+O)  —  ou largue um ficheiro aqui",
    "OpenFileDialogFilter": "Ficheiros EPUB (*.epub)|*.epub",
    "Settings": "Definições",
    "LoadingChapters": "A carregar capítulos…",
    "ResetText": "Repor definições de texto",
    "NoBookmarks": "Ainda não há marcadores. Prima B para adicionar um.",
    # About/Support keys where European Portuguese differs from Brazilian.
    "AboutBrandBlurb": "A Green Yoga Inc cria software e ferramentas digitais pensados para a leitura, o bem-estar e a tecnologia prática.",
    "AboutWebsiteLink": "Sítio Web da Green Yoga",
    "AboutContactSupport": "Contactar o suporte",
    "AboutLicenseUnavailable": "Não foi possível carregar o texto da licença. Esta aplicação é distribuída sob a Licença MIT.",
    "SupportDisclosure": "Contactar o suporte carrega o sítio Web da Green Yoga (greenyogainc.com) dentro desta janela. É necessária ligação à Internet, e a política de privacidade do sítio Web da Green Yoga aplica-se a qualquer informação que submeta.",
    "SupportOpenInBrowser": "Abrir no navegador Web",
    "SupportEmail": "Contactar o suporte por e-mail",
    "SupportLoading": "A carregar página de suporte…",
    "SupportLoadFailed": "Não foi possível carregar a página de suporte. Verifique a sua ligação à Internet e tente novamente, ou utilize uma das opções abaixo.",
    "ContinuousSectionTitleFormat": "Secção {0}",
}

HEADER = """<?xml version="1.0" encoding="utf-8"?>
<root>
  <resheader name="resmimetype">
    <value>text/microsoft-resx</value>
  </resheader>
  <resheader name="version">
    <value>2.0</value>
  </resheader>
  <resheader name="reader">
    <value>System.Resources.ResXResourceReader, System.Windows.Forms, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089</value>
  </resheader>
  <resheader name="writer">
    <value>System.Resources.ResXResourceWriter, System.Windows.Forms, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089</value>
  </resheader>
"""


def escape(s: str) -> str:
    return s.replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;")


def build() -> None:
    missing_report: list[str] = []
    for locale, values in TRANSLATIONS.items():
        missing = set(ORDER) - set(values)
        extra = set(values) - set(ORDER)
        if missing or extra:
            missing_report.append(f"{locale}: missing={sorted(missing)} extra={sorted(extra)}")
    if missing_report:
        raise SystemExit("Key mismatch:\n" + "\n".join(missing_report))

    for locale, values in TRANSLATIONS.items():
        lines = [HEADER]
        for key in ORDER:
            lines.append(f'  <data name="{key}" xml:space="preserve"><value>{escape(values[key])}</value></data>\n')
        lines.append("</root>\n")
        out = SRC / f"Strings.{locale}.resx"
        out.write_text("".join(lines), encoding="utf-8")
        print(f"Wrote {out}")


if __name__ == "__main__":
    build()
